### ISSUE TITLE
v3.5.5 unable to reference remote resource via commit hash

### ISSUE THREAD

**Issue by JTarasovic** [kubernetes-sigs/kustomize#2494] opened 2020-05-15 19:41 UTC
This minimal `kustomization.yaml` will build with v3.5.4 but errors in v3.5.5

```yaml
resources:
- github.com/coreos/kube-prometheus?ref=5b9341cad
```

```
2020/05/15 14:37:30 Error cloning git repo: Cloning into '/tmp/kustomize-774769430'...
warning: Could not find remote branch 5b9341cad to clone.
fatal: Remote branch 5b9341cad not found in upstream origin
Error: accumulating resources: accumulateFile "accumulating resources from 'github.com/coreos/kube-prometheus?ref=5b9341cad': evalsymlink failure on '/home/jason/Development/forks/tmp/github.com/coreos/kube-prometheus?ref=5b9341cad' : lstat /home/jason/Development/forks/tmp/github.com: no such file or directory", loader.New "trouble cloning git repo https://github.com/coreos/kube-prometheus.git in /tmp/kustomize-774769430: exit status 128"
```

**Comment by saravanakumar-periyasamy** [comment] 2020-05-15 20:12
btw @JTarasovic I don't think it was downloading the specific sha in v3.5.4 also. It silently errors out and downloads the `master` branch always. I had to use the tag or branch to make it pin. 

You can find more details here - https://github.com/kubernetes-sigs/kustomize/issues/2072#issuecomment-624431493

**Comment by JTarasovic** [comment] 2020-05-15 20:25
ahh. shoot. I saw what looks to be the same thing in #2444 as well.

**Comment by JTarasovic** [comment] 2020-05-16 00:03
Yeah, the problem currently is either that we assumed a ref is only a branch/tag or that -b takes a ref.

https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/git/cloner.go#L39

Unfortunately, neither is true.

**Comment by mr-karan** [comment] 2020-05-18 08:04
Yep, wasn't able to make it work with `?ref=branch/tag` either. https://github.com/kubernetes-sigs/kustomize/issues/2444#issuecomment-630015608

**Comment by michaelgeorgeattard** [comment] 2020-05-19 10:13
https://github.com/kubernetes-sigs/kustomize/issues/2444#issuecomment-630725244

**Comment by RyanSquared** [comment] 2020-05-26 21:17
I think at some point kustomize may have moved from using go-getter ? The documentation here: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md states that it uses go-getter, which correctly clones and checks out.

**Comment by chancez** [comment] 2020-05-26 21:53
https://github.com/kubernetes-sigs/kustomize/issues/2538 seems like it may be related.

**Comment by pwittrock** [comment] 2020-05-27 19:07
cc @monopole @seans3

**Comment by monopole** [comment] 2020-05-27 21:22
dupe of #2444, fix is in  #2537, which is in [v3.6.1](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.6.1)

**Closed by monopole** 2020-05-27 21:22 UTC

**Comment by JTarasovic** [comment] 2020-05-27 21:46
tested against master. looks good. thanks all!

**Comment by monopole** [comment] 2020-05-27 21:51
thanks for confirming!
