### ISSUE TITLE
YAML to JSON parsing error when using a numeric as a key in a map?

### ISSUE THREAD

**Issue by spstarr** [kubernetes-sigs/kustomize#5001] opened 2023-01-26 01:12 UTC
### What happened?

I am trying to apply a Anthos Service Mesh, Istio `PeerAuthentication` CR and get error:

This is from Config Sync which is running `kustomize build` to render the output:

```
Error: error marshaling into JSON: json unsupported type: map[interface {}]interface {} For more information, see https://g.co/cloud/asm-errors#knv1068
```

However, if I quote the numeric keys then all works as normal. I'm not sure if this is a parsing error in Kustomize.

### What did you expect to happen?

The Resource to apply without error.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../charts
helmCharts:
- name: myapp
  version: 0.0.1
  releaseName: my-config-connector
  namespace: default
  valuesFile: values-dev.yaml
```

```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: istio-peerauth
  namespace: mynamespace
spec:
  selector:
    matchLabels:
       app.kubernetes.io/cluster: mynamespace
  portLevelMtls:
    1234:
      mode: PERMISSIVE
    5000:
      mode: PERMISSIVE
    9000:
      mode: PERMISSIVE
  mtls:
    mode: STRICT
```

### Kustomize version

Config Sync 1.14.0 managed Kustomize 

### Operating system

Other

**Comment by kamuridesu** [comment] 2023-01-26 17:37
I have some suspects about what's causing this behavior. Let me check to confirm if I am right.

**Comment by spstarr** [comment] 2023-01-26 18:22
This is a duplicate of #4928 and I didn't notice ... pending merge

**Comment by KnVerey** [comment] 2023-02-02 04:13
Agreed, this is a duplicate of either that issue or possibly https://github.com/kubernetes-sigs/kustomize/issues/3446

/triage duplicate
/close

**Closed by KnVerey** 2023-02-02 04:13 UTC
Labels: kind/bug, triage/duplicate
