### ISSUE TITLE
integer keys causing problems

### ISSUE THREAD

**Issue by jwilner** [kubernetes-sigs/kustomize#4133] opened 2021-08-20 19:00 UTC
**Describe the bug**

A resource containing integer map keys causes kustomize to barf.

```shell
$ kustomize version
{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-07-01T01:00:35+01:00 GoOs:darwin GoArch:amd64}
$ cat kustomization.yaml
resources:
  - https://github.com/knative/net-istio/releases/download/v0.24.0/release.yaml
$ kustomize build
Error: map[string]interface {}{"apiVersion":"security.istio.io/v1beta1", "kind":"PeerAuthentication", "metadata":map[string]interface {}{"labels":map[string]interface {}{"networking.knative.dev/ingress-provider":"istio", "serving.knative.dev/release":"v0.24.0"}, "name":"domainmapping-webhook", "namespace":"knative-serving"}, "spec":map[string]interface {}{"portLevelMtls":map[interface {}]interface {}{8443:map[string]interface {}{"mode":"PERMISSIVE"}}, "selector":map[string]interface {}{"matchLabels":map[string]interface {}{"app":"domainmapping-webhook"}}}}: json: unsupported type: map[interface {}]interface {}
``` 

I would expect this to simply roundtrip the resource. The problematic section of YAML is:

```yaml
---
# Allows the Webhooks to be reached by kube-api with or without
# sidecar injection and with mTLS PERMISSIVE and STRICT.
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "webhook"
  namespace: "knative-serving"
  labels:
    serving.knative.dev/release: "v0.24.0"
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    matchLabels:
      app: webhook
  portLevelMtls:
    8443:
      mode: PERMISSIVE
```

The following minimal yaml produces the same error:

```yaml
---
# Allows the Webhooks to be reached by kube-api with or without
# sidecar injection and with mTLS PERMISSIVE and STRICT.
kind: "PeerAuthentication"
metadata:
  name: foo
foo:
  8443: ok
```

**Comment by KnVerey** [comment] 2021-09-01 16:41
/triage duplicate
Duplicate of #3446
/close

**Closed** 2021-09-01 16:41 UTC
Labels: kind/bug, triage/duplicate, needs-triage
