### ISSUE TITLE
patchesStrategicMerge fix with go FixKustomizationPreMarshalling is broken

### ISSUE THREAD

**Issue by Noamrok** [kubernetes-sigs/kustomize#5499] opened 2023-12-24 13:13 UTC
### What happened?

We have the following kustomization.yaml file:
```yaml
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
patchesStrategicMerge:
- gateway-patches/gcp-us-west1.yaml
- gateway-patches/azure-eastus.yaml
- gateway-patches/aws-eu-central-1.yaml
- health-domain-patches/dal3x-health-patch.yaml
- health-domain-patches/ric2x-health-patch.yaml
- health-domain-patches/fra1x-health-patch.yaml
```

We are running kustomize using the golang api v0.15.0, and using the `FixKustomizationPreMarshalling` function.
The output is:
```yaml
patches:
  - patch: gateway-patches/gcp-us-west1.yaml
  - patch: gateway-patches/azure-eastus.yaml
  - patch: gateway-patches/aws-eu-central-1.yaml
  - patch: health-domain-patches/dal3x-health-patch.yaml
  - patch: health-domain-patches/ric2x-health-patch.yaml
  - patch: health-domain-patches/fra1x-health-patch.yaml
```

and the kustomize on this file returns the following error:
```
trouble configuring builtin PatchTransformer with config: `
patch: gateway-patches/gcp-us-west1.yaml
`: unable to parse SM or JSON patch from [patch: “gateway-patches/gcp-us-west1.yaml”]
```

### What did you expect to happen?

We solved it by manually converting `patchesStrategicMerge` to `patches`:
```yaml
patches:
  - path: gateway-patches/gcp-us-west1.yaml
  - path: gateway-patches/azure-eastus.yaml
  - path: gateway-patches/aws-eu-central-1.yaml
  - path: health-domain-patches/dal3x-health-patch.yaml
  - path: health-domain-patches/ric2x-health-patch.yaml
  - path: health-domain-patches/fra1x-health-patch.yaml
```

We think this is the intended output that suppose to be.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
patchesStrategicMerge:
- aaa.yaml
```

### Expected output

```yaml
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
patches:
- path: aaa.yaml
```

### Actual output

```yaml
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
patches:
- patch: aaa.yaml
```

### Kustomize version

v0.15.0

### Operating system

None

**Comment by charles-chenzz** [comment] 2023-12-27 02:08
> We are running kustomize using the golang api v0.15.0

what's the output of ``kustomize version`` ? 
in the lastest version the patchesStrategicMerge is deprecated and we suggest using patches

**Comment by charles-chenzz** [comment] 2023-12-27 14:53
you're doing make kustomizer object and call Run to perform like kustomize cli right? I haven't try it before, I may need time to reproduce it to see what happen

**Comment by koba1t** [comment] 2023-12-28 03:40
@Noamrok 
Currently, kustomize uses whether that field string is a readable file to determine whether to write a `path` or `patch` field.
https://github.com/kubernetes-sigs/kustomize/blob/0c461d61df5c616a50cbb308305d4a1f052f263a/api/types/kustomization.go#L275-L287

Have you put valid files when you exec fix?

**Comment by Noamrok** [comment] 2023-12-28 14:48
Hi,
Thank you for the response.

My files are valid (suppose to be) and this is what I dont understand, in my case:

```yaml
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
patchesStrategicMerge:
- gateway-patches/gcp-us-west1.yaml
```

the  `gateway-patches/gcp-us-west1.yaml` is a path and not inline string so it suppose to do a path not a patch.
`gateway-patches/gcp-us-west1.yaml` file content is:

```yaml
apiVersion: core.apigw.btp.sap.com/v1alpha1
kind: A
metadata:
  name: B
  namespace: C
spec:
  lb:
    address: D
```

**Comment by koba1t** [comment] 2023-12-28 15:26
@Noamrok 

I wasn't reproducing in my computer with `kustomize cli v5.3.0`.

```
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
patches:
- path: gateway-patches/gcp-us-west1.yaml
```

Maybe you failed to call `FixKustomizationPreMarshalling` or other functions.

**Comment by tal-sapan** [comment] 2023-12-31 14:17
Hi,

After further investigating @Noamrok's issue I think the problem is that the current working directory wasn't set to the folder of the `kustomization.yaml` file, so the issue can be fixed by changing the current working directory.

I think it would be useful to be able to create a `filesys.FileSystem` implementation which can get the current working directory as input, similar to `os.DirFS()`, so it isn't necessary to actually switch the working directory before calling `FixKustomizationPreMarshalling`.

**Closed** 2024-05-29 15:14 UTC
Labels: lifecycle/rotten, kind/bug, needs-triage
