### ISSUE TITLE
Possible to use a (private) repo that's not on Github?

### ISSUE THREAD

**Issue by aodj** [kubernetes-sigs/kustomize#585] opened 2018-11-29 13:16 UTC
I've been trying to get a kustomize working against a private repo hosted on Bitbucket, but after defining it like so:

```yaml
bases:
- git::bitbucket.org:org/rep.git//base/overlay/aws
```

I get the following exception:

```
Error: loadResMapFromBasesAndResources: couldn't make ldr for git::bitbucket.org:org/repo.git//base/overlay/aws: error downloading 'bitbucket.org:org/repo.git': /usr/local/bin/git exited with 128: Cloning into '/var/folders/gl/tb8ktf4n0j532y_x4x_hbfmsyg9d2b/T/kustomize-372791287/repo'...
alexander@bitbucket.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I'm able to `git clone` this repo wihtout problem, and I don't know why the git cloning in kustomize is using the username of `alexander@bitbucket.org` .

Whilst looking through the source for kustomize, here in the repo, I noticed that the code seems to only support git bases from github.com; is this the case? Is it possible to use private git repos as bases? The documentation seems to be nonexistent on this point, so I'm not sure where I'm supposed to be able to find information on this.

Thanks for your help on this matter.

**Comment by aodj** [comment] 2018-11-29 18:17
I installed it using brew, and `brew info kustomize` returns `1.0.10`. Note that `kustomize version` returns a git version stamp which lists build time as epoch 😄

**Comment by Liujingfang1** [comment] 2018-11-29 20:19
Can you try the head? @monopole recently refactored the GitHub loader part.

**Comment by aodj** [comment] 2018-11-29 22:04
Yea, about that... The `simpleGitCloner` only seems to work with Github repos, which effectively rules out me running this against my private Bitbucket repo. 

[Relevant code snippet](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/loader/gitcloner.go#L68-L72):
```go
cmd := exec.Command(
    gitProgram,
    "clone",
    "https://github.com/"+repo+".git",
    checkoutDir)
```

**Comment by aodj** [comment] 2018-12-03 12:09
Trying it with head I get even less:

```bash
alexander at mbp in ~/Documents/bitbucket/my-local-repo on master*
$ GIT_TRACE=1 go run ../../github/kustomize/kustomize.go build
Error: loadResMapFromBasesAndResources: couldn't make ldr for git::bitbucket.org:org/repo.git//base/overlay/aws: trouble cloning git::bitbucket.org:org/repo.git//base/overlay/aws: exit status 128


exit status 1
```
Note that I've not really used Go before, so if there's a better way to be running this code, then I'm happy to rerun it after guidance. It would be good to update the documentation at the same time 😉

**Comment by Liujingfang1** [comment] 2018-12-08 00:10
@aodj I'm working on the fix. What is the url if you want to clone this repo  `git::bitbucket.org:org/rep.git`?

**Comment by aodj** [comment] 2018-12-10 20:45
@Liujingfang1 I don't understand your last message. Could you explain what you mean?

**Comment by aodj** [comment] 2018-12-10 21:00
I took a look at #612 and I think I get it now. When I clone the repo i simply run `git clone git@bitbucket.org:org/repo.git` which works, since I've got my ssh key in my ssh agent.

There was some documentation that said i needed to set the syntax to pull from remote repos using the Hashicorp go-getter syntax hence the `git::` prefix, since I'm forcing it to recognise it as a Git repo.

The problem is that, even when forcing the git loader,  the git configuration that's being used doesn't seem to be using any of my settings, and so isn't picking up my private key.

The current lack of support for non Github repos is purely a secondary issue since the `1.0.10` version available via Homebrew does (did) support loading non Github repos, and so despite the fact that you're fixing the issue, which I appreciate, what I actually want to be able to do is provide the ssh key and username that will allow me to connect with the existing `1.0.10` functionality.

**Comment by Liujingfang1** [comment] 2018-12-10 21:37
`go-getter` was removed and we rewrote the gitloader in 1.0.11. 
With the PR #612 , you can use `git@bitbucket.org:org/repo.git`.

**Comment by asm76** [comment] 2018-12-11 10:43
How about this origin - ssh://git@gitlab.example.com:10022/stub/stub/stub-repo.git ?

**Comment by Liujingfang1** [comment] 2018-12-11 18:09
@asm76 When you run `git clone`, do you use `git clone ssh://git@gitlab.example.com:10022/stub/stub/stub-repo.git`?

**Comment by asm76** [comment] 2018-12-12 09:05
@Liujingfang1 yes, exactly

**Comment by asm76** [comment] 2018-12-12 09:40
![screenshot](https://user-images.githubusercontent.com/8554962/49860521-019d9500-fe0b-11e8-86de-917bbc3ba2d7.png)

**Comment by asm76** [comment] 2018-12-13 12:46
Is this issue resolved? I can't  succeed even with the head

```
$ ls  ~/go/bin/
$ go get sigs.k8s.io/kustomize
$ ls  ~/go/bin/
kustomize
$ ~/go/bin/kustomize version
Version: {KustomizeVersion:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:unknown GoArch:unknown}
$ ~/go/bin/kustomize build projects/infra/kubernetes/thanos-confd-base/
Error: loadResMapFromBasesAndResources: couldn't make ldr for git::ssh://git@gitlab2.sqtools.ru:10022/infra/kubernetes/thanos-base.git?ref=v0.1.0: trouble cloning git::ssh://git@gitlab2.sqtools.ru:10022/infra/kubernetes/thanos-base.git?ref=v0.1.0: exit status 128
```

**Comment by aodj** [comment] 2018-12-13 13:41
Same error here, using latest from source.
```
$ ~/Documents/github/kustomize/bin/kustomize build
Error: loadResMapFromBasesAndResources: couldn't make ldr for git::bitbucket.org:org/repo.git: trouble cloning git::bitbucket.org:org/repo.git: exit status 128
$ ~/Documents/github/kustomize/bin/kustomize version
Version: {KustomizeVersion:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:unknown GoArch:unknown}
$ git branch
* master
$ git show
commit f0f8aad2bb7ef09996825bce30896be568af9589 (HEAD -> master, origin/master, origin/HEAD)
Merge: 38873aa 259cecd
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Wed Dec 12 10:11:51 2018 -0800

    Merge pull request #612 from Liujingfang1/gitloader

    add handling function for remote url hostname
```

**Comment by Liujingfang1** [comment] 2018-12-13 17:47
@aodj Can you try `git@bitbucket.org:org/repo.git`?
@asm76 The repo URL in your case is not handled correctly by the code. I'll work on a fix.

**Comment by aodj** [comment] 2018-12-14 09:19
@Liujingfang1, using `git@bitbucket.org:org/repo.git` I get:
```
$ ~/Documents/github/kustomize/bin/kustomize build
Error: loadResMapFromBasesAndResources: couldn't make ldr for git@bitbucket.org:org/repo.git: absolute root dir '/Users/alexander/Documents/bitbucket/my-local-repo/git@bitbucket.org:org/repo.git' does not exist
```
If I specify the `git::` override I get:
```
$ ~/Documents/github/kustomize/bin/kustomize build
Error: loadResMapFromBasesAndResources: couldn't make ldr for git::git@bitbucket.org:org/repo.git: trouble cloning git::git@bitbucket.org:org/repo.git: exit status 128
```

**Comment by Liujingfang1** [comment] 2018-12-17 18:35
@aodj New change is merged. Can you try it again with `git@bitbucket.org:org/repo.git`?

**Comment by aodj** [comment] 2018-12-19 09:56
Using `git@bitbucket.org:org/repo.git`:
```$ ~/Documents/github/kustomize/bin/kustomize build
Error: loadResMapFromBasesAndResources: couldn't make ldr for git@bitbucket.org:org/repo.git: absolute root dir '/Users/alexander/Documents/bitbucket/my-local-repo/git@bitbucket.org:org/repo.git' does not exist```

If I try simply passing the url on the command line, it gives a similar error:
```$ ~/Documents/github/kustomize/bin/kustomize build git@bitbucket.org:org/repo.git
Error: absolute root dir '/Users/alexander/Documents/bitbucket/my-local-repo/git@bitbucket.org:org/repo.git' does not exist```

```
$ git show
commit 048c1dde97f647f334c391c21fccb3cfe5af6fd0 (HEAD -> master, origin/master, origin/HEAD)
Merge: dd17174 949fd51
Author: Jeff Regan <jeff.regan@gmail.com>
Date:   Tue Dec 18 17:09:45 2018 -0800

    Merge pull request #647 from monopole/yaTest

    Yet another kusttarget test.
```

**Comment by Liujingfang1** [comment] 2018-12-19 18:33
@aodj I couldn't reproduce this error. The one I see is `Error: trouble cloning git@bitbucket.org:org/repo.git:`, which means the URL is recognized as a remote repo. Your error means it is recognized as a local directory.

**Comment by Liujingfang1** [comment] 2018-12-19 19:10
try `ls -l ~/Documents/github/kustomize/bin/kustomize` or `~/Documents/github/kustomize/bin/kustomize version`

**Comment by aodj** [comment] 2018-12-20 13:52
> try `ls -l ~/Documents/github/kustomize/bin/kustomize` or `~/Documents/github/kustomize/bin/kustomize version`

```
$ ls -l ~/Documents/github/kustomize/bin/kustomize
-rwxr-xr-x  1 alexander  ****\****  30101716 Dec 19 09:48 /Users/alexander/Documents/github/kustomize/bin/kustomize
$ ~/Documents/github/kustomize/bin/kustomize version
Version: {KustomizeVersion:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:unknown GoArch:unknown}
```

**Comment by hagmonk** [comment] 2018-12-20 18:01
Ok this is a little freaky. Based on a comment from @Liujingfang1 in Slack, I realized I had checked out kustomize in the wrong place in the GOPATH:

Works:

```
$ cd $GOPATH/src/sigs.k8s.io/kustomize
$ git rev-parse --short HEAD
900152f7
$ go run ./kustomize.go build git@github.redacted.com:schmoo/cabal.git//test/scaleio-crasher/node120
<YAML output>
```

Does not work:

```
$ cd $GOPATH/src/kubernetes-sigs/kustomize
$ git rev-parse --short HEAD
900152f7
$ go run ./kustomize.go build git@github.redacted.com:schmoo/cabal.git//test/scaleio-crasher/node120
Error: absolute root dir '/Users/lburton/src/github.com/kubernetes-sigs/kustomize/git@github.redacted.com:schmoo/cabal.git/test/scaleio-crasher/node120' does not exist
exit status 1
```

Same goes for running tests, I can't run `go test` unless I'm in the "sigs.k8s.io" repo. I thought go was supposed to make all this stuff easy?? 😬

**Comment by Liujingfang1** [comment] 2018-12-20 18:15
@hagmonk We changed the pkg path of kustomize to be under `sigs.k8s.io` a couple of months ago. If you look at the [installation instruction](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/INSTALL.md), it is suggested to use
```
go get sigs.k8s.io/kustomize
```

**Comment by hagmonk** [comment] 2018-12-20 18:17
@Liujingfang1 got it, thanks for the clarification. And the good news is, remote `kustomize build` is working again 🎉

**Comment by Liujingfang1** [comment] 2018-12-20 18:19
Great

**Comment by Liujingfang1** [comment] 2018-12-20 18:19
Please open a new issue if you see this happen again, thanks.

**Closed by Liujingfang1** 2018-12-20 18:19 UTC
Labels: kind/bug

**Comment by aodj** [comment] 2018-12-21 09:49
Clearly there's something I'm missing here:

```
alexander at mbp in ~/Documents/github/kustomize/src/sigs.k8s.io/kustomize on master
$ go run ./kustomize.go build git@bitbucket.org:org/repo.git
Error: absolute root dir '/Users/alexander/Documents/github/kustomize/src/sigs.k8s.io/kustomize/git@bitbucket.org:org/repo.git' does not exist
exit status 1
```
