### ISSUE TITLE
Problem with arrays

### ISSUE THREAD

**Issue by thyn** [kubernetes-sigs/kustomize#2744] opened 2020-07-22 07:36 UTC
I have patch file like

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ingress-haproxy
  namespace: ingress-haproxy
spec:
  template:
    spec:
      containers:
      - name: ingress-haproxy-container
        ports:
        - name: http1
          containerPort: 80
          hostPort: 80
          hostIP: ip1
        - name: https1
          containerPort: 443
          hostIP: ip1
          hostPort: 443
        - name: stats1
          containerPort: 1936
          hostPort: 8000
          hostIP: 	ip1
        - name: http2
          containerPort: 80
          hostPort: 80
          hostIP: ip2
        - name: https2
          containerPort: 443
          hostIP: ip2
          hostPort: 443
        - name: stats2
          containerPort: 1936
          hostPort: 8000
          hostIP: ip2
        - name: http3
          containerPort: 80
          hostPort: 80
          hostIP: ip3
        - name: https3
          containerPort: 443
          hostIP: ip3
          hostPort: 443
        - name: stats3
          containerPort: 1936
          hostPort: 8000
          hostIP: ip3
---

```

if I build it by kustomize 3.6.1 everything is working normally.
Kustomize 3.8.1 breaks array 
{Version:kustomize/v3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T00:58:46Z GoOs:linux GoArch:amd64}

```
    ports:
        - containerPort: 80
          hostIP: ip1
          hostPort: 80
          name: http1
        - containerPort: 443
          hostIP: ip1
          hostPort: 443
          name: https1
        - containerPort: 1936
          hostIP: ip1
          hostPort: 8000
          name: stats1
        - containerPort: 80
          hostIP: ip1
          hostPort: 80
          name: http1
        - containerPort: 443
          hostIP: ip1
          hostPort: 443
          name: https1
        - containerPort: 1936
          hostIP: ip1
          hostPort: 8000
          name: stats1
        - containerPort: 80
          hostIP: ip1
          hostPort: 80
          name: http1
        - containerPort: 443
          hostIP: ip1
          hostPort: 443
          name: https1
        - containerPort: 1936
          hostIP: ip1
          hostPort: 8000
          name: stats1
```

**Comment by Shell32-Natsu** [comment] 2020-08-11 18:37
Please provide full information about the issue, including you resources files, patch config files (if there is) and kustomization file.

**Comment by Shell32-Natsu** [comment] 2020-08-11 18:39
Sorry sent the comment by mistake. This is duplicated with https://github.com/kubernetes-sigs/kustomize/issues/2767. @monopole

**Comment by monopole** [comment] 2020-09-16 20:20
Closing as dupe of #2767, thanks!

**Closed by monopole** 2020-09-16 20:20 UTC
