### ISSUE TITLE
configMapGenerator does not accept number as data key

### ISSUE THREAD

**Issue by dosmanak** [kubernetes-sigs/kustomize#4430] opened 2022-01-28 09:44 UTC
**Describe the bug**

The kustomize build fails with number in configMapGenerator key

**Files that can reproduce the issue**
```
$ cat kustomization.yaml ; echo ===;  kubectl kustomize .
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: test-cm-with-numberkeys
    literals:
      - "1=A"
===
Error: map[string]interface {}{"apiVersion":"v1", "data":map[interface {}]interface {}{1:"A"}, "kind":"ConfigMap", "metadata":map[string]interface {}{"name":"test-cm-with-numberkeys-7bb2t568gt"}}: json: unsupported type: map[interface {}]interface {}
```
```
$ cat kustomization.yaml ; echo ===;  kubectl kustomize .
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: test-cm-with-numberkeys
    literals:
      - "'1'=A"
===
apiVersion: v1
data:
  '''1''': A
kind: ConfigMap
metadata:
  name: test-cm-with-numberkeys-87487b6hk2
```
**Expected output**
```
apiVersion: v1
data:
  1: A
kind: ConfigMap
metadata:
  name: test-cm-with-numberkeys-87487b6hk2
```
resp.
```
apiVersion: v1
data:
  '1': A
kind: ConfigMap
metadata:
  name: test-cm-with-numberkeys-87487b6hk2
```

**Kustomize version**

$ kustomize version
{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-06-30T22:49:26Z GoOs:linux GoArch:amd64}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

**Platform**

Linux

**Additional context**

haproxy ingress controller uses keys with numbers for errorfiles
https://www.haproxy.com/documentation/kubernetes/latest/configuration/controller/#--configmap-errorfiles

**Comment by larstiq** [comment] 2022-01-28 13:01
Looking at `kubectl explain configmap.data` it says

```
DESCRIPTION:
     Data contains the configuration data. Each key must consist of alphanumeric
     characters, '-', '_' or '.'. Values with non-UTF-8 byte sequences must use
     the BinaryData field. The keys stored in Data must not overlap with the
     keys in the BinaryData field, this is enforced during validation process.
```

Combined with the yaml tendency to interpret numbers as numbers (hence always take care for Pod env vars to quote them), it does look to me like `haproxy` is producing invalid configmaps and should instead quote the keys.

**Comment by dosmanak** [comment] 2022-01-28 14:42
I have verified the configmap is really using string as key and haproxy is accepting it.
But kustomize does not allow event string with number only which is also described in this issue.

**Comment by natasha41575** [comment] 2022-01-28 18:40
This is a duplicate of https://github.com/kubernetes-sigs/kustomize/issues/3446, which we are aware of and are including in our 2022 roadmap. Please check that issue for updates.

/kind duplicate
/close

**Closed** 2022-01-28 18:41 UTC
Labels: kind/bug, needs-triage
