### ISSUE TITLE
go install sigs.k8s.io/kustomize/kustomize/v4@v4.0.1

### ISSUE THREAD

**Issue by tullo** [kubernetes-sigs/kustomize#3628] opened 2021-02-24 10:59 UTC
Experienced with:

`go version go1.16 linux/amd64`

**Describe the bug**

`go install sigs.k8s.io/kustomize/kustomize/v4@v4.0.1`

**Expected output**

Installation succeeds.

**Actual output**

Installation fails:
```sh
sigs.k8s.io/kustomize/kustomize/v4@v4.0.1
	The go.mod file for the module providing named packages contains one or
	more exclude directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Comment by Shell32-Natsu** [comment] 2021-02-24 17:26
Duplicate of #3618 

Looks like an issue with Go 1.16. You can use this [script](https://github.com/kubernetes-sigs/kustomize/blob/master/hack/install_kustomize.sh) to install kustomize binary.

**Closed by Shell32-Natsu** 2021-02-24 17:26 UTC
