### ISSUE TITLE
verify-kustomize-repo stalling locally

### ISSUE THREAD

**Issue by annasong20** [kubernetes-sigs/kustomize#4755] opened 2022-08-11 03:36 UTC
**Describe the bug**

Running `make verify-kustomize-repo` stalls for an indefinite amount of time at `make lint` on `/cmd/config`. 

**Expected output**

All checks should complete successfully.

**Actual output**

The following is the beginning of the log. Many such printouts follow.

<img width="794" alt="Screen Shot 2022-08-10 at 2 32 34 PM" src="https://user-images.githubusercontent.com/40309066/184060881-2551c5b8-aae0-409e-b375-ef61c46fb1d1.png">

**Kustomize version**

The current master branch is on commit  [416eed97](https://github.com/kubernetes-sigs/kustomize/commit/416eed97c49aa8e9ea44d627c15dafd395b61739). Note that this occurs after I update my `go` version to 1.18 to accommodate kustomize's use of go 1.18 workspaces. 

**Platform**

macOS. Note that the command runs fine on Linux, though slow.

**Comment by KnVerey** [comment] 2022-08-11 15:59
* Which version of golangci-lint are you using? The error shown looks like it could be caused by running an older version of gomoddirectives that is missing https://github.com/ldez/gomoddirectives/commit/3ce9a6500b555d88b44e6f7ef7dafe4d88c7084b. The fix is in golangci-lint 1.46.0 and newer, and per our makefile we should be using 1.46.2. 
* Does this still happen if if you run `make lint` in cmd/config directly?
* What is the value of `go env GOWORK` for you?

**Comment by annasong20** [comment] 2022-08-11 17:44
> * Which version of golangci-lint are you using? The error shown looks like it could be caused by running an older version of gomoddirectives that is missing [ldez/gomoddirectives@3ce9a65](https://github.com/ldez/gomoddirectives/commit/3ce9a6500b555d88b44e6f7ef7dafe4d88c7084b). The fix is in golangci-lint 1.46.0 and newer, and per our makefile we should be using 1.46.2.

Ahh, yes, this was the problem. I thought that the Makefile version was the version running, but of course it was from an older build. 🤦‍♀️ Thank you so much, Katrina!!

**Closed** 2022-08-11 17:45 UTC
Labels: kind/bug, needs-triage
