### ISSUE TITLE
Add selectorLabels property, to prevent overwriting immutable selector labels with common label values

### ISSUE THREAD

**Issue by rcomanne** [kubernetes-sigs/kustomize#3718] opened 2021-03-12 15:26 UTC
**Is your feature request related to a problem? Please describe.**  
We are migrating towards kubernetes and using kustomize with it, but a lot of us are experiencing 'unexpected' behaviour, which is that when a commonLabel changes, it will fail deploying, because all labels are added as selectors as well, which are immutable.

**Describe the solution you'd like**  
I thought it might be possible to add another option, selectorLabels, which will add the provided labels as selectors, and only add the commonLabels as labels, not as selectors as well.
For instance, like this;
```yaml
commonLabels:
  app.kubernetes.io/owner: ATeam

selectorLabels:
  app.kubernetes.io/name: my-app
```

**Describe alternatives you've considered**  
The alternative we have now, is to add the labels in the file(s) we want ourselves, so we can change them when needed. However, this goes against the whole idea of Kustomize in my opinion.

**Comment by monopole** [comment] 2021-03-17 21:42
Dupe of #1009, which is now reopened.

FWIW see https://github.com/kubernetes-sigs/kustomize/issues/1009#issuecomment-496694715

Feel free to chime in there, appreciate your view here.

**Closed by monopole** 2021-03-17 21:42 UTC
Labels: area/plugin, kind/feature
