### ISSUE TITLE
allow set docker image via a flag

### ISSUE THREAD

**Issue by SongGithub** [kubernetes-sigs/kustomize#447] opened 2018-10-10 06:24 UTC
I understand that currently users can set image tag. However, that would mean the image repo reference is kind of hard coded into base template. 

In my case, my clients ECR repo is an ENV VAR, ECR_REPO=`12345.ecr.dcr.amazonaws.com/foo:123`.it would be great if we could `kustomize set image $ECR_REPO` to set the base layer dynamically.

**Comment by schweikert** [comment] 2018-10-10 07:04
Duplicate of #402

**Comment by Liujingfang1** [comment] 2018-10-16 16:59
close as duplication

**Closed by Liujingfang1** 2018-10-16 16:59 UTC
