### ISSUE TITLE
make install with kubebuilder, and the error "Version v3.8.5 does not exist"  is reported

### ISSUE THREAD

**Issue by njnuwjq** [kubernetes-sigs/kustomize#4618] opened 2022-05-05 06:43 UTC
**Describe the bug**

enviroment is ,

c5337840@C02GW0H7Q05N wjq-testOperator % kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1

c5337840@C02GW0H7Q05N wjq-testOperator % kustomize version
{Version:kustomize/v4.5.2 GitCommit:9091919699baf1c5a5bf71b32ca73a993e98088b BuildDate:2022-02-09T23:19:28Z GoOs:darwin GoArch:arm64}

follow the instruction of this page, 
https://book.kubebuilder.io/quick-start.html 

as i run the make install, the following error occurs,
c5337840@C02GW0H7Q05N wjq-testOperator % curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- 3.8.5 /Users/c5337840/goProj/wjq-testOperator/bin
Version v3.8.5 does not exist.

 and i can find it's the same as https://github.com/kubernetes-sigs/kustomize/issues/3154, and the bug should be fixed in 2020,
c5337840@C02GW0H7Q05N wjq-testOperator % curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- 4.5.2 /Users/c5337840/goProj/wjq-testOperator/bin
c5337840@C02GW0H7Q05N wjq-testOperator % 

tried to replace the version with 4.5.2 , and nothing returned
and change the version number in the Makefile, a new error occured,
c5337840@C02GW0H7Q05N wjq-testOperator % make install
/Users/c5337840/goProj/wjq-testOperator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- 4.5.2   /Users/c5337840/goProj/wjq-testOperator/bin
make: *** [/Users/c5337840/goProj/wjq-testOperator/bin/kustomize] Error 56

searched and nothing found, so could any pls look at this issue?

**Files that can reproduce the issue**

**Expected output**

**Actual output**

**Kustomize version**

**Platform**

**Additional context**

**Comment by KnVerey** [comment] 2022-06-08 17:41
Closing as duplicate of https://github.com/kubernetes-sigs/kustomize/issues/4612
/close

**Closed** 2022-06-08 17:41 UTC
Labels: triage/duplicate, kind/releasing
