### ISSUE TITLE
images doesn't apply from all layers

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#803] opened 2019-02-21 01:55 UTC
If I have the below, and am doing `kustomize build overlays/dev/fluent-bit`, if I put 'images' in environments/dev/kustomization.yaml they are ignored.
If i put them in overlays/dev/kustomization.yaml they are processed.
[issue.tar.gz](https://github.com/kubernetes-sigs/kustomize/files/2887287/issue.tar.gz)

attached shows.

```
├── apps
│   ├── fluent-bit
│   │   ├── daemonset.yaml
│   │   └── kustomization.yaml
│   └── kustomization.yaml
├── environments
│   └── dev
│       ├── imagePullSecret.txt
│       └── kustomization.yaml
└── overlays
    ├── dev
    │   └── fluent-bit
    │       └── kustomization.yaml
    └── kustomization.yaml
```

**Comment by darwin67** [comment] 2019-02-24 09:36
I'm seeing this too but mine get ignored regardless of where I put it and it just doesn't apply at all.

I have a deployment with the following
```yaml
        - name: deck
          image: gcr.io/k8s-prow/deck:v20190220-ef0e29b
```

and tried putting this on both the `base`, `overlay`, then both.
```yaml
vars:
  - name: deck
    newTag: v20190221-d14461a
```

Running
```bash
$ kustomize build overlays/devops  | grep 'v20190221-d14461a'
```

gave me an empty output

**Comment by donbowman** [comment] 2019-02-24 15:56
@darwin67 Don't you want 'images' rather than 'vars'?

**Comment by darwin67** [comment] 2019-02-24 19:00
sorry, not sure why i posted `vars`, it was `images`. updated my previous comment.

**Comment by darwin67** [comment] 2019-02-27 18:48
I tried using `v2.0.2` and it still doesn't work.

**Comment by Liujingfang1** [comment] 2019-02-28 19:19
`images` are not accumulated across base/overlays. Thus `images` declared in base is only visible to that base, not to any overlays. 

@darwin67 What is the original image used in your resources? I guess it is not matched with `deck` so `deck` is ignored.

**Comment by darwin67** [comment] 2019-02-28 23:26
@Liujingfang1 
my bad, I thought it was the `name` of the container so I was not using the image name.
it was working fine once I tried with the image name so please ignore my comment. :smiley:

**Comment by Liujingfang1** [comment] 2019-03-28 22:40
close this issue as duplicate of #915

**Closed by Liujingfang1** 2019-03-28 22:40 UTC
