### ISSUE TITLE
kustomize build can produce multiple yaml files based on kind instead of a merged single one

### ISSUE THREAD

**Issue by Yejing0609** [kubernetes-sigs/kustomize#4308] opened 2021-11-25 07:42 UTC
Currently it seems `kustomize build` command can only apply the patches and write the merged content into one single file. However, in our process, we need it to print different files based on the `kind` or `file`
for example, the structure is like below
```
.
├── base
│   ├── deployment.yaml
│   ├── hpa.yaml
│   ├── kustomization.yaml
│   └── service.yaml
└── overlays
    ├── dev
    │   ├── hpa.yaml
    │   └── kustomization.yaml
```

when run e.g. `kustomize build --separate-files -o <folder> overlays/dev`, we can get below files with already merged results
```
<folder>
   --hpa.yaml
   --service.yaml
   --deployment.yaml
```

**Comment by KnVerey** [comment] 2021-12-21 20:51
This is a duplicate of https://github.com/kubernetes-sigs/kustomize/issues/897 / https://github.com/kubernetes-sigs/kustomize/issues/55. Now that https://github.com/kubernetes-sigs/kustomize/pull/4065 is in, you can enable the `buildMetadata: [originAnnotations]` option to track where resources came from. If your specific use case requires a particular output directory layout, you can use that information and/or the resource metadata itself to post-process into your desired structure.

/triage duplicate
/close

**Closed** 2021-12-21 20:51 UTC
Labels: kind/feature, triage/duplicate, needs-triage

**Comment by cronjevh** [comment] 2022-10-15 07:14
Powershell gist to move/rename kustomize build output based on `buildMetadata: [originAnnotations]`  https://gist.github.com/cronjevh/8f5c6d24bdc8fee5b798d9fd2776dbf5
