### ISSUE TITLE
VolumeClaimTemplates overwritten by StrategicMergePatch

### ISSUE THREAD

**Issue by tobgu** [kubernetes-sigs/kustomize#819] opened 2019-02-25 10:51 UTC
I have a stateful set with the following volumeClaimTemplate:
```yaml
  volumeClaimTemplates:
  - metadata:
      name: myapp-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast
      resources:
        requests:
          storage: 50Gi
```
When I apply a patch as the below the whole spec is overwritten. I would have assumed only the parts in the patch to have been overwritten.

```yaml
# Patch
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  volumeClaimTemplates:
  - metadata:
      name: myapp-data
    spec:
      resources:
        requests:
          storage: 250Gi

# Result: accessModes and storageClassName are lost
  volumeClaimTemplates:
  - metadata:
      name: myapp-data
    spec:
      resources:
        requests:
          storage: 250Gi
```

Is this the expected behaviour? I can work around it by including `accessModes` and `storageClassName` in the patch but it would be nicer to not have to.

```
$ kustomize version
Version: {KustomizeVersion:v2.0.1 GitCommit:ce7e5ee2c30cc5856fea01fe423cf167f2a2d0c3 BuildDate:2019-02-14T13:47:19+00:00 GoOs:unknown GoArch:unknown}
```

**Comment by pwittrock** [comment] 2019-03-01 18:12
cc @kow3ns 

I believe this is a bug in the StatefulSet API caused by the volumeClaimTemplates not having a merge strategy or key.  You can see on the PodSpec that Volumes are merged by Name.  I would expect StatefuleSetSpec to have something similar.

As a work around, you can use the jsonPatch format, which doesn't rely on a merge key.

- [podspec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#podspec-v1-core)
- [statefulsetspec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#statefulsetspec-v1-apps)
  -

**Closed** 2019-03-01 18:13 UTC
Labels: kind/bug, sig/apps

**Comment by pwittrock** [comment] 2019-03-01 18:16
Closing in favor of kubernetes/kubernetes#74819

**Comment by stawii** [comment] 2020-07-10 12:55
Please read https://github.com/kubernetes/kubernetes/issues/74819#issuecomment-656222231

How come this is related to StatefulSet API? Kustomize should just generate output - it would work on first run, but you cannot change values later (due to API limitation at the moment).
Kustomize role is to patch/merge manifests based on user input. Otherwise there is no (easy) way to change storage requests size without needing to redefine every other option.

**Comment by AlekSi** [comment] 2020-09-08 08:45
Please re-open

**Comment by rocketraman** [comment] 2021-06-06 13:03
This was closed in favor of https://github.com/kubernetes/kubernetes/issues/74819 but that issue us closed now too, so basically there is no good solution.
