### ISSUE TITLE
[Feature Request]please provide a way to list builtin plugins

### ISSUE THREAD

**Issue by dfang** [kubernetes-sigs/kustomize#3193] opened 2020-11-07 04:08 UTC
**Is your feature request related to a problem? Please describe.**

try to follow this [guide](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md) with the latest release 3.8.6 or built from the master branch of source code ,
both got `loading generator plugins: unable to load builtin ~G_builtin_HelmChartInflationGenerator` error

```
kustomize-helm-demo λ  kustomize build --enable_alpha_plugins dev
Error: accumulating resources: accumulateFile "accumulating resources from '../base': '/private/tmp/kustomize-helm-demo/base' must resolve to a file", accumulateDirector: "recursed accumulation of path '/private/tmp/kustomize-helm-demo/base': loading generator plugins: unable to load builtin ~G_builtin_HelmChartInflationGenerator"
```

I can confirm the [commit](https://github.com/kubernetes-sigs/kustomize/commit/e75d4fc87d48e815d468b04b785522cbb6e15ec8) is the master branch

```
λ  git log --pretty=oneline | grep e75d4fc87d48e815d468b04b785522cbb6e15ec8
e75d4fc87d48e815d468b04b785522cbb6e15ec8 convert helm inflator to builtin plugin
```

**Describe the solution you'd like**

list plugins that has built into binary like `nginx -V` or `caddy list-modules`

**Comment by Shell32-Natsu** [comment] 2020-11-08 01:10
The HelmChatInflationGenerator is in master but will be in next release. Our doc website is following the latest master branch instead of the latest release now.

**Comment by dfang** [comment] 2020-11-08 14:51
why it doesn't work when i built from master branch ？

**Comment by Shell32-Natsu** [comment] 2020-11-09 18:50
Please provide your error message from the master branch.

**Comment by memelet** [comment] 2020-11-10 01:35
I just build from master and see the same error
```
$ ~/go/bin/kustomize version                                           master 🐍 .venv
{Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:linux GoArch:amd64}
```

```
$ ~/go/bin/kustomize build .                                           master 🐍 .venv
Error: loading generator plugins: unable to load builtin ~G_builtin_HelmChartInflationGenerator
```

**Comment by Shell32-Natsu** [comment] 2020-11-10 01:38
@memelet what's your kustomization file? How do you invoke helm transformer?

**Comment by Shell32-Natsu** [comment] 2020-11-10 18:01
I can confirm the issue. Will fix it soon.

**Comment by Shell32-Natsu** [comment] 2020-11-10 18:06
Issue is covered by #3202

**Comment by mikebz** [comment] 2020-11-17 00:44
looks like the PR is merged.  What else should we do to close this issue?

**Comment by Shell32-Natsu** [comment] 2020-11-17 00:50
@mikebz There is no PR for this feature. #3202 is for fixing HelmChartInflator bug.

**Closed** 2020-11-18 19:13 UTC
Labels: area/cli, kind/feature, priority/backlog, triage/accepted

**Comment by arnav3000** [comment] 2022-06-20 15:46
@Shell32-Natsu - If I want to see the "enabled" builtin plugins for Kustomize, is there a command for same ?
