### ISSUE TITLE
Question: base and overlays

### ISSUE THREAD

**Issue by jojijohn** [kubernetes-sigs/kustomize#3757] opened 2021-03-25 20:13 UTC
I have a base and overlay like shown below, and I was expecting that 
`kubectl apply -k overlays/dev` or `kustomize build overlays/dev/` would give me a ConfigMap which has the common annotations and common labels applied to it. It looks like it doesn't use the directives in the base file. What could I be doing wrong? Any help is appreciated!

base/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonAnnotations:
  reloader.stakater.com/match: "true"
  description: "App ConfigMap"
commonLabels:
  purpose: app-config
generatorOptions:
  disableNameSuffixHash: true
```

overlays/dev/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
namespace: qa
configMapGenerator:
  - name: app-config
    files:
      - app.properties
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.14", GitCommit:"f238f5142728be4033c37aa0ad69bf806090beae", GitTreeState:"clean", BuildDate:"2020-11-11T13:03:54Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ kustomize build overlays/dev/
apiVersion: v1
data:
  app.properties: |
    foo=bar
kind: ConfigMap
metadata:
  name: app-config-8t86dkf76m
  namespace: qa
```

**Comment by natasha41575** [comment] 2021-03-25 22:16
I believe this a duplicate of another issue. Please see the explanation in the comment here: https://github.com/kubernetes-sigs/kustomize/issues/2647#issuecomment-718935820

The transformers defined in bases will only be applied to the base resources. You can take a look at [components](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/components.md) and see if that suits your use case

**Comment by natasha41575** [comment] 2021-03-31 20:42
I am closing this issue, but feel free to reopen if you have further questions or concerns.

**Closed by natasha41575** 2021-03-31 20:42 UTC
Labels: kind/support
