### ISSUE TITLE
Another potential issue around kind:Namespace

### ISSUE THREAD

**Issue by pb-adrianbezzina** [kubernetes-sigs/kustomize#5192] opened 2023-06-07 12:23 UTC
### What happened?

I have the following manifest:

```yaml
apiVersion: servicebus.azure.com/v1api20210101preview
kind: Namespace
metadata:
  name: servicebus
spec:
  azureName: servicebus
  location: australiaeast
```

and with a transformer configured like so:

```yaml
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: AzureNamePostfix
suffix: -devtest
fieldSpecs:
  - path: spec/azureName
```

The transformation doesn't apply after a _kustomize build_ - and the original manifest is the end result of the build

Seems to be similar to issue #5072 where having a resource of KIND namespace is confusing the kustomize command - if this is found to be a issue - would be wise to check all places there is logic around **_Kind: Namespace_**

### What did you expect to happen?

Manifest:

```yaml
apiVersion: servicebus.azure.com/v1api20210101preview
kind: Namespace
metadata:
  name: servicebus
spec:
  azureName: servicebus
  location: australiaeast
```

and with a transformer configured like so:

```yaml
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: AzureNamePostfix
suffix: -devtest
fieldSpecs:
  - path: spec/azureName
```

New Manifest:

```yaml
apiVersion: servicebus.azure.com/v1api20210101preview
kind: Namespace
metadata:
  name: servicebus
spec:
  azureName: servicebus-devtest
  location: australiaeast
```

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources.yaml
transformers:
  - env.yaml
```

```yaml
# resources.yaml
apiVersion: servicebus.azure.com/v1api20210101preview 
kind: Namespace
metadata:
  name: servicebus
spec:
  azureName: servicebus
  location: australiaeast
```

```yaml
# env.yaml
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: AzureNamePostfix
suffix: -devtest
fieldSpecs:
  - path: spec/azureName
```

### Expected output

```yaml
apiVersion: servicebus.azure.com/v1api20210101preview 
kind: Namespace
metadata:
  name: servicebus
spec:
  azureName: servicebus-devtest
  location: australiaeast
```

### Actual output

```yaml
apiVersion: servicebus.azure.com/v1api20210101preview 
kind: Namespace
metadata:
  name: servicebus
spec:
  azureName: servicebus
  location: australiaeast
```

### Kustomize version

5.0.3

### Operating system

Linux

**Comment by annasong20** [comment] 2023-06-24 01:08
Hi @pb-adrianbezzina, thank you for the issue report. The problem is that [the name suffix transformer is hard-coded to skip all resources with `kind: Namespace`](https://github.com/kubernetes-sigs/kustomize/blob/master/kustomize/commands/internal/kustfile/kustomizationfile.go#L115C20-L115C34).

The fix for this issue would be to change the current namespace GVK to reflect only the k8s built-in `Namespace` object. Like in #5072, this is currently not as simple as specifying the `Group` and `Version` fields on the GVK because the built-in `Namespace` object has an empty group, which the GVK code interprets as any group. If `Group` is the empty string and `Version: v1`, the current issue would be fixed, but any custom object with non-empty `Group`, `Version: v1`, and `kind: Namespace` would suffer from the same no-op that this issue describes.

In the short term, we could hard-code this logic into the prefix, suffix transformers, much like in #5133. In the long run, though, I think it may be worth changing `isMatchGVK`. I agree that kustomize should have built-in knowledge of `Namespace`, as stated in this https://github.com/kubernetes-sigs/kustomize/issues/5072#issuecomment-1480137735. However, isn't kustomize exercising its knowledge by specifying [these GVKs](https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/builtin/suffixtransformer/SuffixTransformer.go#L26-L30) already? It seems more cumbersome hard-coding this logic everywhere we need to use `Namespace` or similar objects. We should ensure that if we change `isMatchGVK`, we find an elegant solution that's backward compatible (definitely possible, for example, we could introduce a boolean to dictate if an empty `Group` is actually empty vs. wildcard). 

@natasha41575 would love to get your thoughts on the feasibility of this.

/triage accepted

**Comment by annasong20** [comment] 2023-07-01 01:25
After discussion, we've agreed that we'd consider changes to `isMatchGVK` IF they aren't breaking.

/unassign

**Closed** 2024-11-27 02:32 UTC
Labels: lifecycle/rotten, kind/bug, needs-triage
