### ISSUE TITLE
Allow using the same base with multiple overlays or transformations

### ISSUE THREAD

**Issue by sethpollack** [kubernetes-sigs/kustomize#38] opened 2018-05-25 17:42 UTC
Here is an example https://github.com/sethpollack/kustomize_example

When you run `kustomize build cluster_a`

You get the following error:

```
Error: there is already an entry: "extensions_v1beta1_Deployment_example.yaml"
```
Is that the desired result? Or should they be treated as unique based on the `namePrefix` that they use?

**Comment by sethpollack** [comment] 2018-06-01 01:17
@monopole I would love to get your thoughts on this?

**Comment by monopole** [comment] 2018-06-05 18:30
IMO, this is a dupe of #18, or a very legitimate complaint about a terrible error message :)

I see you've started on #18, let's see what happens after that.

**Comment by monopole** [comment] 2018-06-05 18:41
I'm not sure if this is about namespaces or about a desire to wrap two overlays with a third
 kustomization that allows the overlays to be build with one command rather than two.  We can clear that up shortly

**Comment by sethpollack** [comment] 2018-06-05 18:43
I want two deployments with the same name and the same namespace with different prefixes. But the check happens before the prefix transform runs.

**Comment by monopole** [comment] 2018-06-05 18:56
Please state the desired end result in yaml :)

**Comment by monopole** [comment] 2018-06-05 18:59
Or lets just wait till your #54 is in.  The application_test in that PR should define a starting point for further behavior improvements.

**Comment by sethpollack** [comment] 2018-06-05 19:03
It would look like 
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    cluster: a
  name: example
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: example
    cluster: a
    env: prod
  name: prod-example
  namespace: example
spec:
  selector:
    matchLabels:
      app: example
      cluster: a
      env: prod
  template:
    metadata:
      labels:
        app: example
        cluster: a
        env: prod
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: example
    cluster: a
    env: stag
  name: stag-example
  namespace: example
spec:
  selector:
    matchLabels:
      app: example
      cluster: a
      env: stag
  template:
    metadata:
      labels:
        app: example
        cluster: a
        env: stag
    spec:
      containers:
      - image: nginx
        name: nginx
```

**Comment by sethpollack** [comment] 2018-06-20 14:03
another example of needing to use the same base multiple times would be #126 if I wanted to create multiple cronjobs I would get the same error 

```
Error: there is already an entry: "batch_v2alpha1_CronJob_example.yaml"
```

**Comment by Liujingfang1** [comment] 2018-06-20 18:41
@sethpollack I propose a different approach instead of using the same base with multiple overlays. We can have some notion to let kustomize know that it deals with multiple kustomizations instead of only one. Then for each of them, process it as usual. Then we avoid this problem.
The format is like this
```
kustomizations:
- ./prod
- ./stag

commonLabels:
  cluster: a
```

**Comment by sethpollack** [comment] 2018-06-20 18:45
That would work.

**Comment by droot** [comment] 2018-06-20 21:30
@sethpollack would like to hear your feedback about SOLUTION1 that @Liujingfang1 suggested above.

**Comment by sethpollack** [comment] 2018-06-21 03:32
@droot The goal for me would be to have a single kustomization file that represents my entire cluster. 

Also there are other areas where the second solution will help out such as reusing the same base resource multiple times with different patches. 

For example if I want several cronjobs with different names, schedules, and commands - with the current setup I would not be able to use patches and would need to copy the entire cronjob for each variant of it.

**Comment by Liujingfang1** [comment] 2018-07-27 22:48
#204 should have fixed this problem.

**Comment by Liujingfang1** [comment] 2018-07-27 22:55
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/multibases/README.md

**Closed by Liujingfang1** 2018-07-27 22:55 UTC
