### ISSUE TITLE
404 Error on Tutorial Page

### ISSUE THREAD

**Issue by thepaulmacca** [kubernetes-sigs/kustomize#4340] opened 2021-12-11 16:19 UTC
Not sure if you're aware or not, but the Tutorial page is currently showing a 404 error https://kustomize.io/tutorial

Thanks

**Comment by natasha41575** [comment] 2021-12-13 21:53
Duplicate of https://github.com/kubernetes-sigs/kustomize/issues/4333, will be tracked in https://github.com/kubernetes-sigs/kustomize/issues/4338

**Closed by natasha41575** 2021-12-13 21:53 UTC
Labels: needs-kind, needs-triage
