### ISSUE TITLE
Remove Default Addition of Block Chomp (|-) on ConfigMaps that don't end with New Line

### ISSUE THREAD

**Issue by amahesh98** [kubernetes-sigs/kustomize#4602] opened 2022-04-22 16:33 UTC
**Describe the bug**

When calling ByteReader.read() on a ConfigMap that doesn't end with a new line, if there is a pipe on the keys, then the last pipe gets replaced with a block chomp indicator (|-). This can be seen through the following flow on a valid yaml string

```
s := "some valid yaml string"
br := kio.ByteReader{
	Reader:                bytes.NewReader([]byte(s)),
	OmitReaderAnnotations: true,
}

rNodes, err := br.Read()
str, err := rNodes[0].String()
fmt.Printf("%v\n", str)
```

**Files that can reproduce the issue**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config-map
  namespace: my-namespace
data:
  base-test: |
    DummyKey: DUMMY_VALUE
    PrintLogs: true
  deployment-abc: |
    DummyKey: DUMMY_VALUE
```

The above will replace `deployment-core-platform-service: |` with `deployment-core-platform-service: |-` since it doesn't end with a new line

Whereas

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config-map
  namespace: my-namespace
data:
  base-test: |
    DummyKey: DUMMY_VALUE
    PrintLogs: true
  deployment-abc: |
    DummyKey: DUMMY_VALUE

```

The above will not since it ends with a new line.

**Expected output**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config-map
  namespace: my-namespace
data:
  base-test: |
    DummyKey: DUMMY_VALUE
    PrintLogs: true
  deployment-abc: |
    DummyKey: DUMMY_VALUE
```

**Actual output**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config-map
  namespace: my-namespace
data:
  base-test: |
    DummyKey: DUMMY_VALUE
    PrintLogs: true
  deployment-abc: |-
    DummyKey: DUMMY_VALUE
```

**Kustomize version**

kustomize/kyaml v0.10.19

**Platform**

Linux / macOS

**Additional context**

We are willing to submit a fix ourselves, just wanted to confirm first if this is actually the expected behavior

**Comment by amahesh98** [comment] 2022-04-22 16:35
Commenting this as well for visiblity: We are willing to submit the fix ourselves, just wanted to confirm first if this is actually the expected behavior

**Comment by KnVerey** [comment] 2022-05-12 01:10
Are you able to reproduce with a more recent version of kyaml? I tried adding your sample as a test in kio, and was unable to reproduce. If you can reproduce on master, please open a PR with a test case and we can go from there. Issues like this may be coming from go-yaml, which makes them more difficult to fix (we're in the process of making a fork that will make this easier in the future). That said, since I can't reproduce, I'm wondering if it was indeed a go-yaml issue that was fixed with the version bump included in kyaml 0.11.0.

```go
// This test passes

func TestIssue4602(t *testing.T) {
	s := `apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config-map
  namespace: my-namespace
data:
  base-test: |
    DummyKey: DUMMY_VALUE
    PrintLogs: true
  deployment-abc: |
    DummyKey: DUMMY_VALUE
`

	br := ByteReader{
		Reader:                bytes.NewReader([]byte(s)),
		OmitReaderAnnotations: true,
	}

	rNodes, err := br.Read()
	require.NoError(t, err)
	str, err := rNodes[0].String()
	require.NoError(t, err)
	require.Equal(t, s, str)
}
```

**Closed** 2022-07-07 00:30 UTC
Labels: triage/not-reproducible, kind/bug, area/yaml-upstream

**Comment by cbodonnell** [comment] 2022-08-30 15:02
Hi @KnVerey, I was able to reproduce this on master with the test case above by removing the newline at the end of the ConfigMap string, which aligns with what @ashwinmahesh is reporting:

``` go
func TestIssue4602(t *testing.T) {
	s := `apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config-map
  namespace: my-namespace
data:
  base-test: |
    DummyKey: DUMMY_VALUE
    PrintLogs: true
  deployment-abc: |
    DummyKey: DUMMY_VALUE`

	br := ByteReader{
		Reader:                bytes.NewReader([]byte(s)),
		OmitReaderAnnotations: true,
	}

	rNodes, err := br.Read()
	require.NoError(t, err)
	str, err := rNodes[0].String()
	require.NoError(t, err)
	require.Equal(t, s, str)
}
```

**Comment by KnVerey** [comment] 2022-08-30 15:49
Oh, you're right that I misinterpreted which case what causing the change when I wrote my test. But looking at the results, aren't the desired and actual semantically equivalent? In fact, isn't the actual less prone to ambiguity of intent? For example, if another key is added after `data`, without the block chomp, the `deployment-abc ` content will start ending in a newline.

Regardless, I confirmed that this behaviour is coming from go-yaml, not Kustomize:

```go
func TestIssue4602(t *testing.T) {
	s := `apiVersion: v1
data:
  base-test: |
    DummyKey: DUMMY_VALUE
    PrintLogs: true
  deployment-abc: |
    DummyKey: DUMMY_VALUE
    OtherKey: OTHER_VALUE`

	thing := map[string]interface{}{}
	err := yaml.Unmarshal([]byte(s), thing)
	require.NoError(t, err)
	result, err2 := yaml.Marshal(thing)
	require.NoError(t, err2)
	require.Equal(t, s, string(result))
}
```
```diff
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -5,4 +5,5 @@
        	            	     PrintLogs: true
        	            	-  deployment-abc: |
        	            	+  deployment-abc: |-
        	            	     DummyKey: DUMMY_VALUE
        	            	     OtherKey: OTHER_VALUE
        	            	+
 ```

We are getting close to having our fork in place, but we will only be making critical bug/regression fixes there. If I've understood correctly, this behaviour is semantically correct, so not something that would be eligible.
