### ISSUE TITLE
sigs.k8s.io/kustomize/api release needs to be triggered for kyaml v0.13.10

### ISSUE THREAD

**Issue by pacoxu** [kubernetes-sigs/kustomize#4955] opened 2023-01-04 10:34 UTC
### What happened?

When I upgrade to `hack/pin-dependency.sh sigs.k8s.io/kustomize/kyaml v0.13.10`

```
+++ [0104 04:11:09] Running tests without code coverage and with -race
# k8s.io/kubernetes/vendor/sigs.k8s.io/kustomize/api/internal/plugins/fnplugin
vendor/sigs.k8s.io/kustomize/api/internal/plugins/fnplugin/fnplugin.go:60:9: too many return values
	have (*runtimeutil.FunctionSpec, error)
	want (*runtimeutil.FunctionSpec)
```

This is for `sigs.k8s.io/kustomize/api` has no new release. The change above is in API package.

### What did you expect to happen?

sigs.k8s.io/kustomize/api release needs to be triggered for kyaml v0.13.10

### How can we reproduce it (as minimally and precisely as possible)?

None

### Expected output

None

### Actual output

NA

### Kustomize version

 kyaml v0.13.10

### Operating system

MacOS

**Comment by natasha41575** [comment] 2023-01-04 17:28
Thanks! This is a duplicate of https://github.com/kubernetes-sigs/kustomize/issues/4945. We fell behind on releasing over the holidays and are planning to release next week.

**Closed by natasha41575** 2023-01-04 17:28 UTC
Labels: kind/bug, needs-triage
