### ISSUE TITLE
invalid memory address or nil pointer dereference from `kustomize edit fix --vars`

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#5323] opened 2023-09-08 06:25 UTC
### What happened?

```
kustomize edit fix --vars
# Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10117d1b4]
```

### What did you expect to happen?

Update `vars` to `replacements`

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Expected output

Update `vars` to `replacements`

### Actual output

```
kustomize edit fix --vars
# Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10117d1b4]

goroutine 1 [running]:
sigs.k8s.io/kustomize/api/types.(*Selector).Copy(...)
	sigs.k8s.io/kustomize/api/types/selector.go:32
sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix.writePatchTargets({{0x140007f2e70, 0x16}, {0x0, 0x0}, 0x0, 0x0}, 0x101455b18?, {0x14002674910, 0x1, 0x3?}, ...)
	sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix/convert.go:287 +0x64
sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix.constructTargets({0x140018a7bc0?, 0x1400179cb00?}, 0x1014611d0?, {0x14002674910?, 0x1, 0x1}, {0x14002439b58, 0x1, 0x1})
	sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix/convert.go:244 +0x198
sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix.addTargets(0x140011b3b40, {0x1400179cb00, 0xe}, {0x1400101f200?, 0x9, 0x7?}, {0x1014611d0, 0x1019e2888})
	sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix/convert.go:120 +0x128
sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix.ConvertVarsToReplacements({0x1014611d0, 0x1019e2888}, 0x14000e098c0)
	sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix/convert.go:36 +0x234
sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix.RunFix({0x1014611d0, 0x1019e2888}, {0x101457398, 0x14000010018})
	sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix/fix.go:63 +0xe0
sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix.NewCmdFix.func1(0x1400023af00?, {0x10119029b?, 0x1?, 0x1?})
	sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix/fix.go:35 +0x2c
github.com/spf13/cobra.(*Command).execute(0x1400023af00, {0x140001f9d30, 0x1, 0x1})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x1400027a000)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(0x13267a0?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x1c
main.main()
	sigs.k8s.io/kustomize/kustomize/v5/main.go:14 +0x20
```

### Kustomize version

v5.1.1

### Operating system

None

**Comment by annasong20** [comment] 2023-12-20 18:41
Cannot reproduce. Closing as completed by #5211. Please re-open with more details if this was closed prematurely.
/close

**Closed by annasong20** 2023-12-20 18:41 UTC
Labels: kind/bug, needs-triage
