### ISSUE TITLE
Regression: git resource urls not reliably parsed

### ISSUE THREAD

**Issue by u2mejc** [kubernetes-sigs/kustomize#3137] opened 2020-10-23 01:17 UTC
**Describe the bug**
When defining remote git repos (resources), BitBucket is no longer supported.

**Files that can reproduce the issue**
- kustomization.yaml
```
resources:
  - git@bitbucket.org:example/kustomize-bases.git
```

**Expected output**
No errors.

**Actual output**
```
Error: accumulating resources: accumulateFile "accumulating resources from 'git@bitbucket.org:example/kustomize-bases.git': evalsymlink failure on '/Users/u2mejc/git/rcloud-grafana/k8s/overlays/dev/git@bitbucket.org:example/kustomize-bases.git' : lstat /Users/u2mejc/git/rcloud-grafana/k8s/overlays/dev/git@bitbucket.org:example: no such file or directory", accumulateDirector: "couldn't make target for path '/private/var/folders/8y/nvkx88k54v7g09fx3gnkcsc80000gn/T/kustomize-702317965/repo': unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/private/var/folders/8y/nvkx88k54v7g09fx3gnkcsc80000gn/T/kustomize-702317965/repo'"
```

**Kustomize version**

`{Version:kustomize/v3.8.5 GitCommit:4052cd4fd8c76a17b5f64e32509f3fba9713fe75 BuildDate:2020-10-08T05:35:40+01:00 GoOs:darwin GoArch:amd64}`

**Platform**
Mac OS

**Additional context**

Adding `{"git@bitbucket.org:", "git@bitbucket.org:"},` to `kustomize/api/internal/git/repospec_test.go`'s `hostNamesRawAndNormalized`, triggers a segmentation fault when testing.
```
--- FAIL: TestNewRepoSpecFromUrl (0.00s)
    repospec_test.go:61: problem url lacks orgRepo: git@bitbucket.org:someOrg/someRepo?ref=someBranch
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x110f60d]

goroutine 18 [running]:
testing.tRunner.func1.1(0x1129420, 0x122a670)
        /usr/local/Cellar/go/1.15.2/libexec/src/testing/testing.go:1076 +0x30d
testing.tRunner.func1(0xc000082780)
        /usr/local/Cellar/go/1.15.2/libexec/src/testing/testing.go:1079 +0x41a
panic(0x1129420, 0x122a670)
        /usr/local/Cellar/go/1.15.2/libexec/src/runtime/panic.go:969 +0x175
sigs.k8s.io/kustomize/api/internal/git.TestNewRepoSpecFromUrl(0xc000082780)
        /Users/juclark/go/src/github.com/kubernetes-sigs/kustomize/api/internal/git/repospec_test.go:63 +0x60d
testing.tRunner(0xc000082780, 0x1156308)
        /usr/local/Cellar/go/1.15.2/libexec/src/testing/testing.go:1127 +0xef
created by testing.(*T).Run
        /usr/local/Cellar/go/1.15.2/libexec/src/testing/testing.go:1178 +0x386
exit status 2
FAIL    sigs.k8s.io/kustomize/api/internal/git  0.238s
```

**Related**
#585
#750

**Comment by Shell32-Natsu** [comment] 2020-10-23 18:43
Could you try to run `git clone [REPO]` manually?

**Comment by u2mejc** [comment] 2020-10-23 23:45
> @Shell32-Natsu said:
> Could you try to run git clone [REPO] manually?
```
Cloning into 'kustomize-bases'...
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 14 (delta 1), reused 0 (delta 0)
Receiving objects: 100% (14/14), done.
Resolving deltas: 100% (1/1), done.
```

That works as expected. 😄   The issue was reproducible on master@HEAD, as of yesterday.

**Comment by Shell32-Natsu** [comment] 2020-10-24 00:03
I am not familiar with bitbucket but it looks like I cannot clone the repo.

**Comment by u2mejc** [comment] 2020-10-24 00:58
My apologies, the example is just an example for the text in this ticket. It's a generic git compatible repo. Assuming kustomize uses the native git client on the system, it should simply trying cloning and fail with a git error if it doesn't exist.

The issue technically has nothing to do with bitbucket, it's simply that kustomize's URL/URI parser is failing to recognize this as a valid git URL.

I'm curious looking at the code, any reason not to simply use the builtin URL parser here?

**Comment by u2mejc** [comment] 2020-10-24 01:00
Updated title of issue to clarify. 👍

**Comment by Shell32-Natsu** [comment] 2020-10-24 04:56
OK, bug confirmed. We do have bug in the git spec parser.

What kustomize expect is URL in this format: `[ssh://]git@serverIp[:serverPort]/orgName/repoName[.git]`. So the URLs like following are not parsed correctly
 - `git@bitbucket.org:someOrg/someRepo`: `someOrg` is considered as a part of hostname.
 - `git@bitbucket.org:222:someOrg/someRepo`: same as above.
 - `bitbucket.org:someOrg/someRepo`: hostname is not found since it doesn't start with `git@`.
etc.

**Note:** we have special hack for `github.com` repos so they should be fine.

https://github.com/kubernetes-sigs/kustomize/blob/76a8f034cb906baf1ca0a4f7b62cef785960a0a8/api/internal/git/repospec.go#L102
This part of codes is very complex and in a huge short of comments.

BTW, please make sure that there **is** a kustomization.yaml file in your repo. @u2mejc

**Comment by Shell32-Natsu** [comment] 2020-11-02 04:58
I tried with a bitbucket repo `git@bitbucket.org:shell32-natsu/kustomize-example.git` but I cannot reproduce the issue. Although we actually have bugs in git URL parsing but it shouldn't harm the cloning process. Further more, [`go-getter`](https://github.com/hashicorp/go-getter) is used before git command engaged. In my experiment, `go-getter` can get the repo without issue so our parsing code is not run.

**Comment by Shell32-Natsu** [comment] 2020-11-06 23:28
Close this now. Feel free to reopen.

**Closed by Shell32-Natsu** 2020-11-06 23:28 UTC
Labels: area/api, kind/bug, priority/important-soon, triage/needs-information, triage/not-reproducible

**Comment by u2mejc** [comment] 2020-12-20 16:24
Thank you for taking the time to debug this! 🙏

I was reminded today how annoying seemingly unresolved threads are, when googling for an answer, so this response is simply to close the loop on this resolved issue.

The root issue was I wasn’t able to understand the error message:

> lstat /Users/u2mejc/git/rcloud-grafana/k8s/overlays/dev/git@bitbucket.org:example: no such file or directory"

As memory serves, this is the same error given for missing local resources, which made me think it was treating the url, as a local file name.

My original issue was actually caused when I had forgotten how to pass a valid git url, with a specific path in the git repo: 

ie `https://github.com/hashicorp/go-getter.git//testdata`

This meant that kustomize couldn’t find the kustomize.yml file, which was in a subdirectory of the git repo. I composed this issue, without the sub directory, because I didn’t grok the error.

Hopfully, this helps future travelers! 🚀
