### ISSUE TITLE
panic: interface conversion: interface {} is string, not map[string]interface {}

### ISSUE THREAD

**Issue by christiangda** [kubernetes-sigs/kustomize#3405] opened 2020-12-29 07:57 UTC
**Describe the bug**

After upgrading my kustomize version yesterday, this error start happening

**Files that can reproduce the issue**

```bash
mkdir kubernetes-dashboard
cd kubernetes-dashboard
curl --remote-name --remote-header-name https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml
kustomize create --autodetect --recursive

kustomize build .
```

**Expected output**

The rendering of this `yaml`file: [https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml](https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml)

**Actual output**

```bash
panic: interface conversion: interface {} is string, not map[string]interface {}

goroutine 1 [running]:
sigs.k8s.io/kustomize/api/resmap.getNamespacesForRoleBinding(0xc0001ac960, 0x19)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/resmap/reswrangler.go:417 +0x352
sigs.k8s.io/kustomize/api/resmap.(*resWrangler).SubsetThatCouldBeReferencedByResource(0xc000405260, 0xc0001ac960, 0xb, 0xc00258e901)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/resmap/reswrangler.go:384 +0xdb
sigs.k8s.io/kustomize/api/internal/accumulator.(*nameReferenceTransformer).Transform(0xc001d741a0, 0x555a060, 0xc000405260, 0xc000405260, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/accumulator/namereferencetransformer.go:85 +0x531
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/accumulator/resaccumulator.go:138
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).FixBackReferences(0xc000405240, 0xc000405240, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/accumulator/resaccumulator.go:164 +0xbe
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc00068f580, 0x0, 0x0, 0x5552100, 0x5fb6700)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/target/kusttarget.go:125 +0x7d
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/target/kusttarget.go:106
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc0005c5d20, 0x7ffeefbff9d8, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/krusty/kustomizer.go:77 +0x29b
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.(*Options).RunBuild(0xc0006820e0, 0x54fcfa0, 0xc000010018, 0x1, 0x0)
	/private/tmp/kustomize-20201210-91507-flrdla/kustomize/internal/commands/build/build.go:148 +0xb5
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.NewCmdBuild.func1(0xc000293b80, 0xc0004b5000, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/kustomize-20201210-91507-flrdla/kustomize/internal/commands/build/build.go:70 +0xad
github.com/spf13/cobra.(*Command).execute(0xc000293b80, 0xc0004b4fd0, 0x1, 0x1, 0xc000293b80, 0xc0004b4fd0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000293600, 0x0, 0xffffffff, 0xc00009c058)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/private/tmp/kustomize-20201210-91507-flrdla/kustomize/main.go:19 +0x2a
```

**Kustomize version**

```bash
 kustomize version
{Version:kustomize/v3.9.0 GitCommit:826b5d9792fb67c4d8f8cd59747698ebf0b22720 BuildDate:2020-12-10T22:29:12+00:00 GoOs:darwin GoArch:amd64}
```

**Platform**

macOS Big Sur 11.1

```bash
brew install kustomize
```

**Additional context**

Before this kustomize version, everything was working fine

**Comment by monopole** [comment] 2020-12-30 20:50
Please use https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.8.9
instead.

If have time to help,see if you can repo this in  https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.9.1

**Comment by Shell32-Natsu** [comment] 2021-01-05 18:49
Duplicate of #3340

**Closed by Shell32-Natsu** 2021-01-05 18:49 UTC
