### ISSUE TITLE
kustomize downloads helm charts and then reuses them when new version specified

### ISSUE THREAD

**Issue by justinsb** [kubernetes-sigs/kustomize#5097] opened 2023-03-18 17:47 UTC
### What happened?

I believe this issue has come up a few times, but I think there is a very concrete incorrect behaviour bug that I think we can & should fix.  (I'm happy to work on fixing it if need be).

I was using the helmCharts support, with an upstream cilium chart, version 1.12.5.  When I run kustomize, it automatically downloads the cilium chart into ./charts/cilium-1.12.5.tar.gz, and inflates it into ./charts/cilium.

I then change the chart version to 1.13.1, but kustomize continues to use ./charts/cilium, which is version 1.12.5

### What did you expect to happen?

I would expect it to use the version I specified, given I didn't directly populate `./charts/cilium` (if I had created that directory myself, maybe the behaviour would be more understandable)

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
helmCharts:
- name: cilium
  repo: https://helm.cilium.io/
  version: 1.12.5
  releaseName: cilium
  namespace: kube-system
  valuesInline:
    hubble:
      enabled: false
```

Run `kustomize build`, change the version, the old version is used.

### Kustomize version

main

### Operating system

Linux

**Comment by justinsb** [comment] 2023-03-18 17:53
Currently helm downloads a helm chart every time it is used.

There's an upstream helm "KEP" where they talk about using a content cache: https://github.com/helm/community/pull/185/files

I think a simple fix here could be to download into a temporary directory and not cache it.  That is consistent with the helm behaviour (until the helm KEP is approved / implemented):

> Helm cannot use the chart version in the cache because the identifier is the name and charts version (e.g., `wordpress-1.2.3.tgz`). A name and version is insufficient as the same chart and version could come from two or more different repositories and have different content.

Although we could implement our own mechanisms here for more efficient caching / verification (there is a digest in the index.yaml), I suggest that should instead be done in helm (first), we don't want to build something incompatible.

**Comment by justinsb** [comment] 2023-03-18 17:57
Looks like there's even a PR that is a good starting point: https://github.com/kubernetes-sigs/kustomize/pull/4999 , though I think we should first agree the behaviour (and maybe I should just be using the KRM function instead?)

**Comment by natasha41575** [comment] 2023-03-20 17:31
Thanks for pointing out https://github.com/kubernetes-sigs/kustomize/pull/4999! We must have missed it.

@justinsb Do you have time to give it a quick review? I will find some time to review it as well.

Re: the KRM function, kustomize functions aren't quite mature enough to be the recommended solution, but it is our desired end goal some day.

**Comment by natasha41575** [comment] 2023-03-20 17:35
@justinsb This seems to be a duplicate of https://github.com/kubernetes-sigs/kustomize/issues/4813 it seems, which I acknowledge is old, but I think we can consider it still active. Do you have any concerns with closing this issue and using https://github.com/kubernetes-sigs/kustomize/issues/4813 to track the work?

**Comment by ChristianCiach** [comment] 2023-06-12 17:02
Also a duplicated of https://github.com/kubernetes-sigs/kustomize/issues/3848 (issue by me)

**Closed** 2024-11-08 19:06 UTC
Labels: lifecycle/rotten, kind/bug, triage/duplicate
