### ISSUE TITLE
Kustomize cannot build manifests if a path in the directory is hidden

### ISSUE THREAD

**Issue by barkardk** [kubernetes-sigs/kustomize#5459] opened 2023-11-22 11:15 UTC
### What happened?

I have a dir used for automation purposes in Ubuntu 22.04 `/home/.build_dir/kustomize/app/base/kustomization.yaml`    
if I try to build on that directory I will get a file not found error.  
This works 
```bash 
kustomize build /home/build_dir/kustomize/app/base/ 
```
This does not 
```bash
kustomize build /home/.build_dir/kustomize/app/base/ 
Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory /home/.build_dir/kustomize/app/base/ 
```

### What did you expect to happen?

The manifest should be built as normal 

### How can we reproduce it (as minimally and precisely as possible)?

just put any base kustomization.yaml and try to build it in a hudden directory

### Expected output

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
```

### Actual output

Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory 

### Kustomize version

v5.2.1 on linux Ubuntu 22.04 

### Operating system

Linux

**Comment by natasha41575** [comment] 2023-11-22 17:15
@sarab97, @annasong20 and I are not able to reproduce this on our machines (both MacOS and Linux).

We see that you are trying to do this under the `/home` directory, could you confirm if you get this issue when you do it outside the `/home` directory? We are wondering if this might be a permission issue. 

Closing as the hidden directory issue as reported is not reproducible.

/close

**Closed by natasha41575** 2023-11-22 17:15 UTC
Labels: kind/bug, needs-triage
