### ISSUE TITLE
kustomize broken on Windows absolute paths

### ISSUE THREAD

**Issue by nicks** [kubernetes-sigs/kustomize#2789] opened 2020-07-30 14:43 UTC
From powershell:

```
PS C:\Users\nick> kustomize build \Users\nick\scratch
PS C:\Users\nick> kustomize build .\scratch
PS C:\Users\nick> kustomize build C:\Users\nick\scratch
Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory 'C:\Users\nick\AppData\Local\Temp\kustomize-089348767\repo'
```

The first two invocations work fine. The last invocation tries to create a temp Kustomize directory and then complains it doesn't exist? Why would it do this?

This seems to have broken recently AFAICT 

```
PS C:\Users\nick> kustomize version
{Version:kustomize/v3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T00:58:46Z GoOs:windows GoArch:amd64}
```

**Comment by nicks** [comment] 2020-07-30 15:06
I've confirmed that this worked correctly in kustomize v3.4.0

**Comment by kungfutse** [comment] 2020-09-18 10:40
This issue is still present in version 3.8.3

**Comment by brianpursley** [comment] 2020-10-20 01:31
I reproduced the bug locally, and I think this is a problem in [hashicorp/go-getter](https://github.com/hashicorp/go-getter) and therefore, the "lite" version forked for kustomize, [yujunz/go-getter](https://github.com/yujunz/go-getter)

I submitted a PR to hashicorp go-getter to handle Windows-style absolute paths:
https://github.com/hashicorp/go-getter/pull/284

If this gets merged, then I can submit the same PR (can I cherry-pick across repos? not sure) to yujunz/go-getter.  Then update kustomize to use this new version and it should fix the issue.

/assign

**Comment by brianpursley** [comment] 2021-02-14 20:22
I submitted a PR to go-getter, but it never really got traction.

the problem is basically due to go-getter improperly interpreting the colon after a Windows drive letter as the delimiter of the protocol version of a URL, so it doesn’t see it as a file.

As a workaround, you should be able to do something like `file:///C:/Users/nick/scratch` instead of `C:\Users\nick\scratch`

Otherwise, I think this is a big upstream. I’m going to unassigned myself from this issue, but would be glad to discuss further if someone who cares about this wants to pick it up.

/unassign

**Closed** 2021-04-15 21:25 UTC
Labels: area/api, kind/bug, lifecycle/rotten, priority/backlog, triage/accepted
