### ISSUE TITLE
'ambiguous' replacement of resourceNames in ClusterRole

### ISSUE THREAD

**Issue by mbfr** [kubernetes-sigs/kustomize#4254] opened 2021-10-21 09:35 UTC
**Describe the bug**

I have a deployment and a generated configmap with the same name and I want to create a clusterrole to allow modifying the deployment. When I create this clusterrole, it replaces the resourceName with the hash-suffix named configmap and I can't stop it doing this.

**Files that can reproduce the issue**

kustomization.yaml

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx.yaml

configMapGenerator:
- name: nginx
  literals:
    - A=B
```

nginx.yaml

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-modify
rules:
- apiGroups: [ "" ]
  resources: [ "deployments" ]
  verbs: [ "get", "list", "update", "patch" ]
  resourceNames:
  - nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: nginx

```

**Expected output**

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-modify
rules:
- apiGroups:
  - ""
  resourceNames:
  - nginx
  resources:
  - deployments
  verbs:
  - get
  - list
  - update
  - patch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-mh97k977cd
...
```

**Actual output**
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-modify
rules:
- apiGroups:
  - ""
  resourceNames:
  - nginx-mh97k977cd
  resources:
  - deployments
  verbs:
  - get
  - list
  - update
  - patch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-mh97k977cd
...
```

**Kustomize version**

```
{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-06-30T22:49:26Z GoOs:linux GoArch:amd64}
```

**Platform**

Linux

**Additional context**

I know I can fix this by disabling the hash suffix name on the configmap, or just changing the name of it, but I can't really do either of them in my real manifests for a few reasons.

**Comment by KnVerey** [comment] 2021-11-12 00:08
> Shouldn't the substitution logic be improved so that for Role / ClusterRole, kustomize can look at the resources field (not just the resourceNames field) when making the decision of replacing the name?

Yes, the name reference transformer has a general problem with support for generic resource references. The issue for that one is here: https://github.com/kubernetes-sigs/kustomize/issues/3418

> they already existed for Secret, so you probably want to address these together (either improve the replacement logic or remove the rules for both resources):

Thank you for pointing this out. Since that substitution has been around for ~3 years, I don't think we can remove it. For consistency with that, we should leave the ConfigMap change in too.

I'm going to add a comment to #3418 that the problem is not exclusive to CRDs, then I propose we close this one as a duplicate.

/triage duplicate

**Comment by KnVerey** [comment] 2021-12-22 19:45
Since we've concluded that we cannot just revert the change to configmap handling and will need to address it with the full solution in https://github.com/kubernetes-sigs/kustomize/issues/3418, I'm going to close this issue as a duplicate.

**Closed by KnVerey** 2021-12-22 19:45 UTC
Labels: kind/bug, triage/duplicate, needs-triage
