### ISSUE TITLE
kustomize crashes on the current (v0.21.0) tekton release manifest yaml

### ISSUE THREAD

**Issue by mhubig** [kubernetes-sigs/kustomize#3639] opened 2021-02-26 09:46 UTC
**Describe the bug**

kustomize crashes on the current (v0.21.0) tekton release manifest yaml

**Files that can reproduce the issue**

```shell
mkdir tekton-test
cat <<EOF > tekton-test/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.21.0/release.yaml
EOF
kustomize build tekton-test

Error: map[string]interface {}{"apiVersion":"apiextensions.k8s.io/v1", "kind":"CustomResourceDefinition", "metadata":map[string]interface {}{"labels":map[string]interface {}{"app.kubernetes.io/instance":"default", "app.kubernetes.io/part-of":"tekton-pipelines", "pipeline.tekton.dev/release":"v0.21.0", "version":"v0.21.0"}, "name":"clustertasks.tekton.dev"}, "spec":map[string]interface {}{"conversion":map[string]interface {}{"strategy":"Webhook", "webhook":map[string]interface {}{"clientConfig":map[string]interface {}{"service":map[string]interface {}{"name":"tekton-pipelines-webhook", "namespace":"tekton-pipelines"}}, "conversionReviewVersions":[]interface {}{"v1beta1"}}}, "group":"tekton.dev", "names":map[string]interface {}{"categories":[]interface {}{"tekton", "tekton-pipelines"}, "kind":"ClusterTask", "plural":"clustertasks"}, "preserveUnknownFields":false, "scope":"Cluster", "versions":[]interface {}{map[string]interface {}{"name":"v1alpha1", "schema":map[string]interface {}{"openAPIV3Schema":map[string]interface {}{"type":"object", "x-kubernetes-preserve-unknown-fields":true}}, "served":true, "storage":false, "subresources":map[string]interface {}{"status":map[string]interface {}{}}}, map[interface {}]interface {}{"name":"v1beta1", "schema":map[string]interface {}{"openAPIV3Schema":map[string]interface {}{"type":"object", "x-kubernetes-preserve-unknown-fields":true}}, "served":true, "storage":true, "subresources":map[string]interface {}{"status":map[string]interface {}{}}}}}}: json: unsupported type: map[interface {}]interface {}
```

I think this is because of the [strange merge syntax](https://yaml.org/type/merge.html) within the manifest:

```yaml
- !!merge <<: *version
   name: v1beta1
   storage: true
```

**Kustomize version**

{Version:kustomize/v4.0.1 GitCommit:516ff1fa56040adc0173ff6ece66350eb4ed78a9 BuildDate:2021-02-14T05:58:54+00:00 GoOs:darwin GoArch:amd64}

**Platform**

macOS Big Sur (11.2.1)

**Comment by Shell32-Natsu** [comment] 2021-02-26 18:05
Duplicate of #3614.

close this at first. If we find that this is a different issue we will reopen.

**Closed by Shell32-Natsu** 2021-02-26 18:05 UTC
