### ISSUE TITLE
Strategic Merge Patch doesn't seem to handle character other than basic ascii

### ISSUE THREAD

**Issue by hansanghoon** [kubernetes-sigs/kustomize#3486] opened 2021-01-20 10:16 UTC
**Describe the bug**

If patch file referenced by `patchesStrategicMerge:` has Korean(한글) character in it, kustomize throws bunch of errors.
Korean comment in none-patch doesn't seem to occur trouble.

**Files that can reproduce the issue**

kustomization.yaml
```yaml
resources:
  - web.yaml
patchesStrategicMerge:
  - web-patch.yaml
```

web.yaml
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      # 컨테이너
      - name: app-container
        image: nginx
        ports:
        - containerPort: 80
```

web-patch.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: app-container
        env:
        # keyvalue1
          - name: KEY # keyvalue2
            value: VALUE 
```

**Expected output**

web-patch.yaml has two comments. Those comment should have no effect even if they are written in Korean.

**Actual output**

Various error occurs.

| `#keyvalue1` is | `#keyvalue2` is | result | 
| --- | --- | --- |
| keyvalue1 | 키 | long error stack trace |
| keyvalue1 | 키밸 | long error stack trace |
| keyvalue1 | 키밸류 | `Error: yaml: invalid trailing UTF-8 octet` |
| 키 | keyvalue2 | long error stack trace |
| 키밸 | keyvalue2 | long error stack trace |
| 키밸류 | keyvalue2 | `Error: yaml: invalid trailing UTF-8 octet` |
| 키밸류 | 키밸 | long error stack trace |
| 키밸 | 키밸류 | long error stack trace |
| 키밸류 | 키밸류 | `Error: yaml: invalid trailing UTF-8 octet` |

long error stack trace example

```
panic: runtime error: index out of range [4] with length 3 [recovered]
	panic: runtime error: index out of range [4] with length 3

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc0000bd290)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/yaml.go:276 +0x85
panic(0x525d300, 0xc0027009a0)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:969 +0x1b9
gopkg.in/yaml%2ev3.write(0xc002e0ea80, 0xc0025acd70, 0x3, 0x8, 0xc0000b8730, 0x443eb01)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:90 +0x245
gopkg.in/yaml%2ev3.yaml_emitter_write_comment(0xc002e0ea80, 0xc0025acd70, 0x3, 0x8, 0x1)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:1978 +0x1ae
gopkg.in/yaml%2ev3.yaml_emitter_process_line_comment(0xc002e0ea80, 0xc00080b920)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:1128 +0x6a
gopkg.in/yaml%2ev3.yaml_emitter_emit_block_mapping_value(0xc002e0ea80, 0xc00080b920, 0xc000809501, 0xc000794501)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:817 +0xec
gopkg.in/yaml%2ev3.yaml_emitter_state_machine(0xc002e0ea80, 0xc00080b920, 0x1)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:303 +0x445
gopkg.in/yaml%2ev3.yaml_emitter_emit(0xc002e0ea80, 0xc002e0ecc0, 0xc0025acd80)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:153 +0x14f
gopkg.in/yaml%2ev3.(*encoder).emit(0xc002e0ea80)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:81 +0x39
gopkg.in/yaml%2ev3.(*encoder).emitScalar(0xc002e0ea80, 0xc0001bf100, 0x5, 0x0, 0x0, 0x0, 0x0, 0xc001f5ce02, 0x5fc2780, 0x0, ...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:417 +0x31a
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e0ea80, 0xc000209720, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:559 +0x136f
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e0ea80, 0xc000209540, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:508 +0xb25
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e0ea80, 0xc0002094a0, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:478 +0x5fc
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e0ea80, 0xc000209220, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:512 +0xa6f
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e0ea80, 0xc000209180, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:478 +0x5fc
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e0ea80, 0xc000209040, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:512 +0xa6f
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e0ea80, 0xc000208f00, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:512 +0xa6f
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e0ea80, 0xc000208c80, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:512 +0xa6f
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e0ea80, 0xc000208640, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:512 +0xa6f
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e0ea80, 0xc0002085a0, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:463 +0x245
gopkg.in/yaml%2ev3.(*encoder).nodev(0xc002e0ea80, 0x51f0740, 0xc0002085a0, 0x16)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:421 +0x79
gopkg.in/yaml%2ev3.(*encoder).marshalDoc(0xc002e0ea80, 0x0, 0x0, 0x51f0740, 0xc0002085a0, 0x16)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:101 +0x23a
gopkg.in/yaml%2ev3.(*Encoder).Encode(0xc002bc00f0, 0x51f0740, 0xc0002085a0, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/yaml.go:251 +0xea
sigs.k8s.io/kustomize/kyaml/yaml.String(0xc0002085a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.10.6/yaml/types.go:215 +0x1b3
sigs.k8s.io/kustomize/kyaml/yaml.(*RNode).String(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.10.6/yaml/rnode.go:468
sigs.k8s.io/kustomize/kyaml/yaml.(*RNode).MarshalJSON(0xc003165440, 0x0, 0x0, 0x0, 0x0, 0xc000860340)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.10.6/yaml/rnode.go:674 +0x37a
sigs.k8s.io/kustomize/api/internal/wrappy.(*WNode).MarshalJSON(0xc002bc00e8, 0x0, 0x0, 0x534fa73, 0x21, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/wrappy/wnode.go:219 +0x2e
sigs.k8s.io/kustomize/api/resource.(*Resource).MarshalJSON(0xc000030140, 0x0, 0x0, 0xc000860340, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/resource/resource.go:93 +0x33
sigs.k8s.io/kustomize/kyaml/filtersutil.GetRNode(0x55057e0, 0xc000030140, 0xc002794fc0, 0xc0000bd600, 0x44d2cd9)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.10.6/filtersutil/filtersutil.go:60 +0x35
sigs.k8s.io/kustomize/api/resource.(*Resource).ApplySmPatch(0xc0001080a0, 0xc000030140, 0x3, 0xc00018e701)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/resource/resource.go:491 +0x3b
sigs.k8s.io/kustomize/api/resmap.(*resWrangler).ApplySmPatch(0xc0004d7820, 0xc002bc00c0, 0xc000030a00, 0xc002bc00c0, 0x2)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/resmap/reswrangler.go:593 +0x32a
sigs.k8s.io/kustomize/api/builtins.(*PatchStrategicMergeTransformerPlugin).Transform(0xc00004b880, 0x5562c40, 0xc0004d7820, 0xc000710000, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/builtins/PatchStrategicMergeTransformer.go:77 +0x176
sigs.k8s.io/kustomize/api/internal/target.(*multiTransformer).transform(0xc00047ee20, 0x5562c40, 0xc0004d7820, 0xc000030301, 0x5)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/target/multitransformer.go:40 +0x79
sigs.k8s.io/kustomize/api/internal/target.(*multiTransformer).Transform(0xc00047ee20, 0x5562c40, 0xc0004d7820, 0xc0000303c0, 0x5)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/target/multitransformer.go:35 +0x85
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/accumulator/resaccumulator.go:141
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).runTransformers(0xc00078eec0, 0xc0004d7800, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/target/kusttarget.go:269 +0x24a
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateTarget(0xc00078eec0, 0xc0004d7800, 0x0, 0x4, 0x1)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/target/kusttarget.go:194 +0x28d
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).AccumulateTarget(0xc00078eec0, 0x40, 0xc00078ed00, 0xc0004d6901)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/target/kusttarget.go:155 +0xce
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc00078eec0, 0x0, 0x0, 0x555a820, 0x5fc2780)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/target/kusttarget.go:110 +0x2f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/target/kusttarget.go:106
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc0000bdd20, 0x7ffeefbffbe0, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/krusty/kustomizer.go:77 +0x29b
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.(*Options).RunBuild(0xc000484c40, 0x5505580, 0xc00018a008, 0x1, 0x0)
	/private/tmp/kustomize-20210117-98130-1ym15v8/kustomize/internal/commands/build/build.go:148 +0xb5
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.NewCmdBuild.func1(0xc0001e0000, 0xc00007a220, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/kustomize-20210117-98130-1ym15v8/kustomize/internal/commands/build/build.go:70 +0xad
github.com/spf13/cobra.(*Command).execute(0xc0001e0000, 0xc00007a1f0, 0x1, 0x1, 0xc0001e0000, 0xc00007a1f0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00027d8c0, 0x0, 0xffffffff, 0xc0000460b8)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/private/tmp/kustomize-20210117-98130-1ym15v8/kustomize/main.go:19 +0x2a
```

**Kustomize version**

3.9.2

**Platform**

macOS, installed using homebrew.

**Additional context**

**Comment by Shell32-Natsu** [comment] 2021-01-20 20:21
Duplicate of #3417

**Closed** 2021-01-20 20:21 UTC
