### ISSUE TITLE
Fail to decode yaml that has affinity with versions v3.9.x

### ISSUE THREAD

**Issue by emailbob** [kubernetes-sigs/kustomize#3523] opened 2021-02-01 22:17 UTC
**Describe the bug**

Since kustomize 3.9.x when kustomize changed the way it manipulates YAML using the kyaml module I started getting this error

`2021/02/01 16:46:53 failed to decode ynode: yaml: unmarshal errors:
  line 97: mapping key "affinity" already defined at line 30`

When using the built in HelmChartInflationGenerator if the Helm values file has two affinities set for example
```

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: component
                operator: In
                values:
                  - server
              - key: app
                operator: In
                values:
                  - prometheus
          topologyKey: "kubernetes.io/hostname"
...
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: component
                operator: In
                values:
                  - alertmanager
              - key: app
                operator: In
                values:
                  - prometheus
          topologyKey: "kubernetes.io/hostname"
```

It will throw an error

If they are empty and set like this

```
affinity: {}
...
affinity: {}

```
It will work

**Expected output**

No error

**Actual output**

```
2021/02/01 16:46:53 failed to decode ynode: yaml: unmarshal errors:
  line 97: mapping key "affinity" already defined at line 30
```

**Kustomize version**

v3.9.1 and v3.9.2

**Platform**

All

**Additional context**

I rolled back to v3.8.9 and that version works

**Comment by Shell32-Natsu** [comment] 2021-02-02 18:44
I believe this error is thrown by go-yaml. I suppose that a valid YAML file shouldn't have duplicate keys.

**Comment by rochacon** [comment] 2021-02-10 10:12
Seems like this is a duplicate of #3480

**Comment by Shell32-Natsu** [comment] 2021-02-10 18:16
@rochacon Thanks for pointing out. It's duplicate.

Duplicate of #3480

**Closed by Shell32-Natsu** 2021-02-10 18:16 UTC
Labels: area/kyaml, area/plugin, kind/bug
