### ISSUE TITLE
Failed to update statefulset

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#804] opened 2019-02-21 03:20 UTC
```
The StatefulSet "redis-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```

**Comment by Liujingfang1** [comment] 2019-02-21 17:33
@yujunz Can your provide the configurations to reproduce this error?

**Comment by yujunz** [comment] 2019-02-24 03:31
I don't remember the exact condition. But it seems related to my local modification to the manifest. Maybe I changed something that is immutable. I wonder if `kustomize` can warn it before sending to kubernetes and propose a delete/apply operation instead.

**Comment by Liujingfang1** [comment] 2019-02-28 18:28
In order to warn that, `kustomize` need to be aware of the previous state(or current state on the cluster) of resources. 
Accessing those state is out of scope of Kustomize. Since it need either to store the previous state locally or make kustomize talk to API-server.

**Closed by Liujingfang1** 2019-02-28 18:28 UTC
