### ISSUE TITLE
install_kustomize.sh fails "cp: can't stat './kustomize': No such file or directory"

### ISSUE THREAD

**Issue by Janny221199** [kubernetes-sigs/kustomize#5398] opened 2023-10-19 19:37 UTC
### What happened?

I use the kustomize CLI in my gitlab CICD Pipeline. It always worked. 

Lately my job fails while installing kustomize.  I use the latest version.

Logs of my Gitlab Job:

```
$ curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
cp: can't stat './kustomize': No such file or directory
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 1
```

I use the gitlab-runner 16.3.0~beta.108.g2b6048b4 on green-2.saas-linux-small-amd64.runners-manager.gitlab.com/default

I use `alpine:3.17.0` as image for my pipeline job

It would be really great if that will work again 👍🏻  If you need any help with that, please let me know!

Thank you very much!!

### What did you expect to happen?

Running the installation script properly without any error.

### How can we reproduce it (as minimally and precisely as possible)?

```
.deploy-job:
  image: alpine:3.17.0
  before_script:
    - apk add --no-cache git curl bash
    - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
    - mv kustomize /usr/local/bin/
```

### Expected output

successful kustomize installation

### Actual output

```
$ curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
cp: can't stat './kustomize': No such file or directory
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 1
```

### Kustomize version

latest

### Operating system

Linux

**Comment by sealneaward** [comment] 2023-10-19 19:41
This just broke our gitops ci/cd pipelines as well.

**Comment by maxdanilov** [comment] 2023-10-19 19:47
Looks like introduced by https://github.com/kubernetes-sigs/kustomize/issues/5220: in the `.tar.gz` release artifacts, the `kustomize` binary is now inside the `output` directory (previously was in the root)

**Comment by natasha41575** [comment] 2023-10-19 20:02
We are aware of the problem and have a fix in flight.

**Comment by natasha41575** [comment] 2023-10-19 20:07
This is a duplicate of https://github.com/kubernetes-sigs/kustomize/issues/5396, so closing.

**Closed by natasha41575** 2023-10-19 20:07 UTC
Labels: kind/bug, needs-triage
