### ISSUE TITLE
Long lines are broken with space in them

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/kustomize#3969] opened 2021-06-08 00:03 UTC
**Describe the bug**

When upgrading to the 4.0.5+ from 4.0.4 longs lines with spaces in the yaml are broken.  Looks similiar to #947 but that was fixed in older versions (this wasn't an issue in 3.8.x+).

**Files that can reproduce the issue**
Example:

kustomization.yaml

```
resources:
 - test.yaml
```

test.yaml

```
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: KubeadmControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    postKubeadmCommands:
    - sed -i '\#--listen-client-urls#s#$#,https://127.0.0.1:2379#' /etc/kubernetes/manifests/etcd.yaml
    - echo "DNSStubListener=no" >> /etc/systemd/resolved.conf
    - mv /etc/resolv.conf /etc/resolv.conf.OLD && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
    - systemctl restart systemd-resolved
```

**Expected output**

```
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: KubeadmControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    postKubeadmCommands:
    - sed -i '\#--listen-client-urls#s#$#,https://127.0.0.1:2379#' /etc/kubernetes/manifests/etcd.yaml
    - echo "DNSStubListener=no" >> /etc/systemd/resolved.conf
    - mv /etc/resolv.conf /etc/resolv.conf.OLD && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
    - systemctl restart systemd-resolved
```

**Actual output**

```
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: KubeadmControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    postKubeadmCommands:
    - sed -i '\#--listen-client-urls#s#$#,https://127.0.0.1:2379#' /etc/kubernetes/manifests/etcd.yaml
    - echo "DNSStubListener=no" >> /etc/systemd/resolved.conf
    - mv /etc/resolv.conf /etc/resolv.conf.OLD && ln -s /run/systemd/resolve/resolv.conf
      /etc/resolv.conf
    - systemctl restart systemd-resolved
```

**Kustomize version**
 4.0.5+ including 4.1.x

**Platform**
linux 

**Additional context**

**Comment by Shell32-Natsu** [comment] 2021-06-08 18:17
Looks like this is the issue in go-yaml https://github.com/go-yaml/yaml/issues/387. kustomize depends on go-yaml v2 indirect through sigs.k8s.io/yaml v1.2.0. So we need to wait for sigs.k8s.io/yaml to update.

**Comment by cadiegoc** [comment] 2021-07-26 11:13
Hi,
My team is having the same issue with Kustomize and long lines being broken.
I can see that Kustomize v4.2.0 was released 25 days ago. Do you know if that version fixes it?
If not, do you know if the next version (v4.3.0?) will fix it? If it does, do you know the expected date for the new release?
Thank you in advance!

**Comment by tobernguyen** [comment] 2021-08-19 20:23
I'm experiencing this in `kustomize v3.9.4` too which is the version `ArgoCD v2.0.4` is using.

**Comment by grzesrap** [comment] 2021-09-07 07:33
This bug still exists in version v4.3.0. Is this work scheduled for the next release? Is there any way to fix this bug now?

**Comment by natasha41575** [comment] 2021-09-07 18:18
> This bug still exists in version v4.3.0. Is this work scheduled for the next release? Is there any way to fix this bug now?

The bug is likely in the [go-yaml libraries](https://github.com/go-yaml/yaml) that we use. Kustomize does not have the resources to address this bug at the moment, but anyone is welcome to investigate and submit a PR to either kustomize or go-yaml for review.

**Comment by hancockjt** [comment] 2021-09-22 22:04
This seems to happen for any string longer than 80 characters in your patches. I'm surprised it's not getting a lot more attention. It's a pretty huge limitation. I'm having to resort to using python yaml parsing to handle these operations.

**Comment by zhouhaibing089** [comment] 2021-10-04 20:47
If I understand correctly, kustomize needs to bump kubernetes-sigs/yaml to [v1.3.0][1]?

[1]: https://github.com/kubernetes-sigs/yaml/releases/tag/v1.3.0

**Comment by cadiegoc** [comment] 2021-11-16 07:49
Does anyone know if this issue has been fixed?

**Comment by karlschriek** [comment] 2022-02-03 11:48
Bumping kubernetes-sigs/yaml to v1.3.0 doesn't seem to fix it (at least not by bumping it on v4.3.0, I cannot speak for later releases).

**Comment by karlschriek** [comment] 2022-02-03 12:23
Actually, interesting, I discovered that infinite lines was brought in with go-yaml v2.30 (https://github.com/go-yaml/yaml/releases/tag/v2.3.0) but was then reverted again (apparently largely because the Kubernetes community wanted it) in v2.40 (https://github.com/go-yaml/yaml/releases/tag/v2.4.0)

kubernetes-sigs/yaml v1.3.0 bumps go-yaml to from v2.2.8 to v2.4.0.

I will investigate with v2.3.0, but I am guessing it will have some surprises as well if folks wanted it reverted.

**Comment by karlschriek** [comment] 2022-02-03 17:59
A few things I learnt: kustomize doesn't just use k8s.sigs/yaml but also uses go-yaml directly in several places.
 
There is also a forked go-yaml that is sometimes used.

Anyway, I tried setting all direct references to 2.3.0 and also created a forked k8s.sigs/yaml that a I aet to use 2.3.0 as well. Also had to fork apimachinery since it was also pegged to 2.4.0.

None of this appears to have had any effect. Long lines are still broken up, so either a I am missing a reference somewhere, or the solution requires additional code changes that I have no idea where to implement.

Could anyone from the core kustomize team comment?

**Comment by karlschriek** [comment] 2022-02-03 19:10
Ok so I finally figured it out.

The direct references to go-yaml don't play any role whatsoever. `sigs.k8s.io/yaml` is the key. This needs to at version 1.3.0 so that go-yaml is at 2.4.0 (not 2.3.0, that isn't actually needed).

This right here is where the magic happens: https://github.com/kubernetes-sigs/yaml/blob/v1.3.0/yaml.go#L82.

To have this work without line breaks you just need to call `yaml.FutureLineWrap()` (i.e. this right here https://github.com/go-yaml/yaml/blob/v2.4.0/yaml.go#L476) somewhere (for example within the JSONtoYaml function

If it really is as simple as this, could we get this as command line arg?

**Comment by cprivite** [comment] 2022-03-01 16:38
For the record, kustomize 4.5.2 still exhibits this behavior.

**Comment by cprivite** [comment] 2022-03-01 16:39
@natasha41575 Given that 4.5.2 doesn't fix it and what @karlschriek has found, do you have any further ideas about what needs to happen here?

**Comment by karlschriek** [comment] 2022-03-02 07:36
Let me also link this PR, which would actually solve the issue https://github.com/kubernetes-sigs/kustomize/pull/4222#issuecomment-946785121, although I doubt whether it will be merged in its current form. The consensus from the Kubernetes community seems at the moment to be that the line-wrapping should be kept, since changing it would causes several tests to break. For us it would be sufficient to have kustomize "init" with `yaml.FutureLineWrap()` based on some flag, e.g. `kustomize build --future-line-wrap .`

**Comment by KnVerey** [comment] 2022-04-01 17:27
/close
/kind duplicate

Duplicate of https://github.com/kubernetes-sigs/kustomize/issues/947, which is older / has more history. Please watch that one intead.

**Closed by KnVerey** 2022-04-01 17:27 UTC
Labels: kind/bug, triage/accepted
