### ISSUE TITLE
kustomize changing the yaml formatting

### ISSUE THREAD

**Issue by pentago** [kubernetes-sigs/kustomize#3610] opened 2021-02-16 11:28 UTC
Opening as per unresolved #291 

I've been using a specific yaml format for the kustomization.yaml files. It seems though that when I run the command `kustomize edit set image <image>` the file is reformatted. This is annoying when using gitops as its hard to see what's changed.

Basically, it reindents the resulting file.

My kustomization.yaml template:

- prior to setting image: https://i.imgur.com/B9WGqT5.png
- after setting image: https://i.imgur.com/fEgdPlq.png

**Comment by Shell32-Natsu** [comment] 2021-02-16 17:50
Duplicate of #3559

**Comment by Shell32-Natsu** [comment] 2021-02-16 17:50
We know this issue. Please use #3559 to discuss.

**Closed by Shell32-Natsu** 2021-02-16 17:50 UTC
