### ISSUE TITLE
kustomize edit add resource results in "panic: runtime error: index out of range [-1]"

### ISSUE THREAD

**Issue by HariSekhon** [kubernetes-sigs/kustomize#4304] opened 2021-11-22 12:11 UTC
**Describe the bug** 

```
$ kustomize edit add resource ./controller/clusterrole.yaml 
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
sigs.k8s.io/kustomize/kustomize/v4/commands/internal/kustfile.(*kustomizationFile).parseCommentedFields(0xc0002f5480, 0xc000362000, 0x671, 0x700, 0x0, 0x0)
        /workspace/myClone/kustomize/commands/internal/kustfile/kustomizationfile.go:215 +0x7b6
sigs.k8s.io/kustomize/kustomize/v4/commands/internal/kustfile.(*kustomizationFile).Read(0xc0002f5480, 0x1ba5708, 0xc0002f5480, 0x0)
        /workspace/myClone/kustomize/commands/internal/kustfile/kustomizationfile.go:173 +0x146
sigs.k8s.io/kustomize/kustomize/v4/commands/edit/add.(*addResourceOptions).RunAddResource(0xc000217bc0, 0x17defa0, 0x1ba5708, 0x11e05e0, 0xc000237d80)
        /workspace/myClone/kustomize/commands/edit/add/addresource.go:65 +0x145
sigs.k8s.io/kustomize/kustomize/v4/commands/edit/add.newCmdAddResource.func1(0xc00031e840, 0xc00033c790, 0x1, 0x1, 0x0, 0x0)
        /workspace/myClone/kustomize/commands/edit/add/addresource.go:35 +0x85
github.com/spf13/cobra.(*Command).execute(0xc00031e840, 0xc00033c750, 0x1, 0x1, 0xc00031e840, 0xc00033c750)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001578c0, 0x0, 0x1619a40, 0xc0000301d8)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /workspace/myClone/kustomize/main.go:14 +0x2a
```

kustomization.yaml:

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goldilocks
```

**Kustomize version**

```
kustomize version
{Version:kustomize/v4.1.3 GitCommit:0f614e92f72f1b938a9171b964d90b197ca8fb68 BuildDate:2021-05-20T20:52:40Z GoOs:darwin GoArch:amd64}
```

**Platform**

macOS

**Additional Information**

Was trying to work around the lack of globbing support in Kustomize at this time as per #3205 and other tickets.

**Comment by natasha41575** [comment] 2021-11-22 18:49
Closing as a duplicate of https://github.com/kubernetes-sigs/kustomize/issues/4123, which has been fixed in more recent versions of kustomize.

Please try with an updated version of kustomize, and let me know if you are still seeing the same issue.

**Closed by natasha41575** 2021-11-22 18:49 UTC
Labels: kind/bug, needs-triage

**Comment by HariSekhon** [comment] 2021-11-22 19:03
This is indeed solved in my testing with the latest kustomize 4.4.1, thanks!
