### ISSUE TITLE
Release 3.6.0 compile failed

### ISSUE THREAD

**Issue by liuyangc3** [kubernetes-sigs/kustomize#2534] opened 2020-05-25 09:04 UTC
go 1.14 MacOs
```bash
GO111MODULE=on go get sigs.k8s.io/kustomize/kustomize/v3@v3.6.0

go: downloading sigs.k8s.io/kustomize/kustomize/v3 v3.6.0
go: downloading sigs.k8s.io/kustomize/cmd/config v0.1.11
go: downloading sigs.k8s.io/kustomize/api v0.4.0
go: downloading sigs.k8s.io/kustomize/kyaml v0.1.11
go: downloading github.com/go-openapi/strfmt v0.19.5
go: downloading github.com/go-openapi/validate v0.19.8
go: downloading go.mongodb.org/mongo-driver v1.1.2
go: downloading github.com/asaskevich/govalidator v0.0.0-20190424111038-f61b66f89f4a
go: downloading github.com/go-openapi/errors v0.19.2
go: downloading github.com/go-openapi/runtime v0.19.4
go: downloading github.com/go-openapi/analysis v0.19.5
go: downloading github.com/go-openapi/loads v0.19.4
# sigs.k8s.io/kustomize/kustomize/v3/internal/commands/status/cmd
/Users/yang/go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.6.0/internal/commands/status/cmd/fetch.go:110:19: res.ResourceIdentifier undefined (type wait.ResourceResult has no field or method ResourceIdentifier)
/Users/yang/go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.6.0/internal/commands/status/cmd/print.go:61:48: data.Identifier.GroupKind undefined (type wait.ResourceIdentifier has no field or method GroupKind)
/Users/yang/go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.6.0/internal/commands/status/cmd/util.go:45:25: too many arguments in call to wait.NewResolver
	have (client.Client, meta.RESTMapper, time.Duration)
	want (client.Reader, time.Duration)
/Users/yang/go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.6.0/internal/commands/status/cmd/util.go:84:65: invalid composite literal type wait.ResourceIdentifier
/Users/yang/go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.6.0/internal/commands/status/cmd/wait.go:135:30: resourceState.Identifier.GroupKind undefined (type wait.ResourceIdentifier has no field or method GroupKind)
/Users/yang/go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.6.0/internal/commands/status/cmd/wait.go:135:57: eventResource.ResourceIdentifier undefined (type *wait.EventResource has no field or method ResourceIdentifier)
/Users/yang/go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.6.0/internal/commands/status/cmd/wait.go:136:28: resourceState.Identifier.Namespace undefined (type wait.ResourceIdentifier has no field or method Namespace)
/Users/yang/go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.6.0/internal/commands/status/cmd/wait.go:136:55: eventResource.ResourceIdentifier undefined (type *wait.EventResource has no field or method ResourceIdentifier)
/Users/yang/go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.6.0/internal/commands/status/cmd/wait.go:137:28: resourceState.Identifier.Name undefined (type wait.ResourceIdentifier has no field or method Name)
/Users/yang/go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.6.0/internal/commands/status/cmd/wait.go:137:50: eventResource.ResourceIdentifier undefined (type *wait.EventResource has no field or method ResourceIdentifier)
/Users/yang/go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.6.0/internal/commands/status/cmd/print.go:61:48: too many errors
```

**Comment by devstein** [comment] 2020-05-25 16:08
Same issue as https://github.com/kubernetes-sigs/kustomize/issues/2462

**Comment by monopole** [comment] 2020-05-27 00:49
Dupe of #2462

**Closed by monopole** 2020-05-27 00:49 UTC
