### ISSUE TITLE
[Question] release v4.2.0 does not have windows binary

### ISSUE THREAD

**Issue by dzmitry-lahoda** [kubernetes-sigs/kustomize#4135] opened 2021-08-22 06:12 UTC
was it intentional or just missed?

https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.2.0

**Comment by natasha41575** [comment] 2021-08-23 23:37
Duplicate of https://github.com/kubernetes-sigs/kustomize/issues/4028, https://github.com/kubernetes-sigs/kustomize/issues/4041

To answer your question, something went wrong in the release process for windows. We urgently needed a release for kubectl v1.23 and have not had time to look into it yet.

**Comment by natasha41575** [comment] 2021-08-23 23:37
Closing as a duplicate, keep an eye on #4028 for updates

**Closed by natasha41575** 2021-08-23 23:37 UTC
Labels: triage/duplicate, needs-kind, needs-triage
