### ISSUE TITLE
Adding stringData to a secret with a secretGenerator

### ISSUE THREAD

**Issue by jrab89** [kubernetes-sigs/kustomize#1444] opened 2019-08-13 23:02 UTC
It it possible to add `stringData` values to a secret using a `secretGenerator` with `behavior: merge`?

For example:
```
$ cat my_secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
stringData:
  FIRST_SECRET: foo
$ cat kustomization.yaml
resources:
  - my_secret.yaml
secretGenerator:
  - name: my-secret
    behavior: merge
    literals:
      - SECOND_SECRET=bar
$ kustomize build .
apiVersion: v1
data:
  SECOND_SECRET: YmFy
kind: Secret
metadata:
  annotations: {}
  labels: {}
  name: my-secret
type: Opaque
```

Is there a way for the resulting `my-secret` to have both `FIRST_SECRET: foo` and `SECOND_SECRET: bar` as `stringData`? In this example I could use a JSON patch to accomplish this, but I think it'd be cleaner to use a `secretGenerator` to do this.

Thanks for your help.

**Comment by lwille** [comment] 2019-12-19 14:55
Honestly I don't see why this is not treated as a bug (it's marked as `feature`):

`stringData` should just behave in the same way as `data`; it's completely unintuitive that its content will be replaced even though `kustomize.config.k8s.io/behavior: merge` is annotated in the secretGenerator's output. For the `data` key of existing secrets merging just works fine.

**Comment by Jeffwan** [comment] 2020-02-14 00:55
This definitely should be a feature. 

sometimes, we uses `vars` from secret to replace some contents in the manifests. The problem is `data` give me encoded string and `stringData` is something I need. Seems there's no way to generate StringData or decode string if var is from secret.

**Closed** 2020-03-15 01:09 UTC
Labels: kind/feature, lifecycle/rotten

**Comment by fhivemind** [comment] 2022-07-06 13:33
Can't believe this is still not resolved 😸

**Comment by mtl-wgtwo** [comment] 2023-04-18 10:39
We're definitely interested in this.  It would work nicely with Flux's [post-build variable substitution](https://fluxcd.io/flux/components/kustomize/kustomization/#post-build-variable-substitution) which currently requires stringData in the secret.
