### ISSUE TITLE
install_kustomize.sh returns ./kustomize_v*_linux_amd64.tar.gz: Cannot open: No such file or directory

### ISSUE THREAD

**Issue by yingding** [kubernetes-sigs/kustomize#4268] opened 2021-11-05 13:28 UTC
**Describe the bug**

I am trying to download v3.2.1 of kustomize using the script from [master brauch](https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh) on 4.Nov 2021. I wasn't able to download the script for my desired version v3.2.1.

**Files that can reproduce the issue**

Issue can be reproduced by running:
```
bash install_kustomize.sh 3.2.1
```

**Expected output**

Should install the specified version of kustomize in the PWD

**Actual output**
```console
tar (child): ./kustomize_v*_linux_amd64.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Platform**

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```
**Additional context**
I can not use the latest Kustomize version, since I need the Kustomize V3.2.1 to compile KubeFlow v1.4 and only the Kustomize V3.2.0 and V3.2.1 works. This issue might be related to issue [#4130](https://github.com/kubernetes-sigs/kustomize/issues/4130), since when I tried to install V3.2.0, i hit the bug of issue [#4130](https://github.com/kubernetes-sigs/kustomize/issues/4130), but with V3.2.1 the error output of this issue report occurs.

**Comment by criztovyl** [comment] 2021-11-07 07:13
Alternatively you could manually download the binary from GitHub Releases here:
3.2.0: https://github.com/kubernetes-sigs/kustomize/releases/tag/v3.2.0
3.2.1: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.2.1

**Comment by criztovyl** [comment] 2021-11-07 09:31
Seems `install_kustomize.sh` only supports v3.3.0+.

up to and including 3.2.0 (but not other 3.2.x, see below!)

```bash
opsys=linux  # or darwin, or windows
vers=3.2.0
curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/v$vers |\
  grep browser_download |\
  grep $opsys |\
  cut -d '"' -f 4 |\
  xargs curl -O -L
mv kustomize_*_${opsys}_amd64 kustomize
chmod u+x kustomize
```

for 3.2.1/.2/.3 use:

```bash
# pick one
opsys=linux # or darwin, or windows
vers=3.2.3
curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/v$vers |\
  grep browser_download |\
  grep $opsys |\
  cut -d '"' -f 4 |\
  xargs curl -O -L
mv kustomize_kustomize\.v*_${opsys}_amd64 kustomize
chmod u+x kustomize
```

**Comment by KnVerey** [comment] 2022-01-19 17:07
Duplicate of https://github.com/kubernetes-sigs/kustomize/issues/4130, which has a PR open at https://github.com/kubernetes-sigs/kustomize/pull/4131

/triage duplicate
/close

**Closed** 2022-01-19 17:07 UTC
Labels: kind/bug, triage/duplicate, needs-triage
