### ISSUE TITLE
kustomize does not remove items of an array using strategic merge

### ISSUE THREAD

**Issue by oliver-goetz** [kubernetes-sigs/kustomize#4596] opened 2022-04-21 13:43 UTC
**Describe the bug**

Deleting items from an array using strategic merge patch does not work as expected in my base-overlay scenario.
Instead of removing the items from the list, it replaces the list content.

Please see my example below. The outputs are those of `kustomize build ./001` command. 

**Files that can reproduce the issue**

*Base layer - directory ./000*

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus-rules.yaml
```

prometheus-rules.yaml

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
  name: kubernetes-monitoring-rules
  namespace: monitoring
spec:
  groups:
  - name: kubernetes-system-scheduler
    rules:
    - alert: KubeSchedulerDown
      annotations:
        description: KubeScheduler has disappeared from Prometheus target discovery.
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeschedulerdown
        summary: Target disappeared from Prometheus target discovery.
      expr: |
        absent(up{job="kube-scheduler"} == 1)
      for: 15m
      labels:
        severity: critical
  - name: kubernetes-system-controller-manager
    rules:
    - alert: KubeControllerManagerDown
      annotations:
        description: KubeControllerManager has disappeared from Prometheus target
          discovery.
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubecontrollermanagerdown
        summary: Target disappeared from Prometheus target discovery.
      expr: |
        absent(up{job="kube-controller-manager"} == 1)
      for: 15m
      labels:
        severity: critical
  - name: kubernetes-system-kube-proxy
    rules:
    - alert: KubeProxyDown
      annotations:
        description: KubeProxy has disappeared from Prometheus target discovery.
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeproxydown
        summary: Target disappeared from Prometheus target discovery.
      expr: |
        absent(up{job="kube-proxy"} == 1)
      for: 15m
      labels:
        severity: critical
```

*Overlay - directory ./001*

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../000

patchesStrategicMerge:
- prometheus-rules-merge.yaml
```

prometheus-rules-merge.yaml

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-monitoring-rules
  namespace: monitoring
spec:
  groups:
  - $patch: delete
    name: kubernetes-system-scheduler
  - $patch: delete
    name: kubernetes-system-controller-manager
```

**Expected output**

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
  name: kubernetes-monitoring-rules
  namespace: monitoring
spec:
  groups:
  - name: kubernetes-system-kube-proxy
    rules:
    - alert: KubeProxyDown
      annotations:
        description: KubeProxy has disappeared from Prometheus target discovery.
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeproxydown
        summary: Target disappeared from Prometheus target discovery.
      expr: |
        absent(up{job="kube-proxy"} == 1)
      for: 15m
      labels:
        severity: critical
```

**Actual output**

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
  name: kubernetes-monitoring-rules
  namespace: monitoring
spec:
  groups:
  - $patch: delete
    name: kubernetes-system-scheduler
  - $patch: delete
    name: kubernetes-system-controller-manager

```

**Kustomize version**

`{Version:kustomize/v4.5.4 GitCommit:cf3a452ddd6f83945d39d582243b8592ec627ae3 BuildDate:2022-03-28T23:06:20Z GoOs:darwin GoArch:amd64}`

**Platform**
macOS

**Additional context**

**Comment by pjastrzabek** [comment] 2022-06-17 16:36
There is really no easy and reliable way of removing elements from the list with kustomize.
What I ended up doing was patching via index 
```
/spec/groups/5
```

which cause problems as soon as upstream project will reorder elements.

What would be usefull is to support field expressions in delete patches
/spec/groups/.[name=kubernetes-system-controller-manager]

**Comment by alexis-wefight** [comment] 2022-07-19 08:18
Is there any workaround for this (without using the index number, which is not reliable)? I have exactly the same issue (with the same Prometheus rules I want to remove).

**Comment by KnVerey** [comment] 2022-08-23 20:10
I suspect the problem here is that you're trying to patch a custom resource without providing the schema for it (via the [openapi field](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/openapi/)). By default, SMPs replace arrays.  If you provide a schema with the extensions for `spec.groups` specified and that doesn't fix it, please reopen.

/triage duplicate of https://github.com/kubernetes-sigs/kustomize/issues/4175, https://github.com/kubernetes-sigs/kustomize/issues/4514 and others
/kind support
/remove-kind bug
/triage resolved

**Closed by KnVerey** 2022-08-23 20:10 UTC
Labels: kind/bug, needs-triage
